import test from'node:test';import assert from'node:assert/strict';
import{beginGrab,releaseGrab,advanceStruggle,grabProfile,grabbedFrame,firstPersonGrab,grabSheet,strugglePrompt,StruggleInput,RECOVERY_DURATION,PARASITES}from'../src/grabs.js';
import{tentacleSpan,crossesTentacle,dragCaptive}from'../src/tentacle-path.js';
import{tickTentacles}from'../src/tentacles.js';import{attachParasite,releaseOrphanParasites}from'../src/parasites.js';
import{makeActor,updateActor}from'../src/combat.js';import{sanitizeInput}from'../src/network.js';
import{SPECS}from'../src/atlas.js';import{ACTORS}from'../src/catalog.js';import{encounterPlan}from'../src/encounters.js';import{makeWorld}from'../src/world.js';
const player=()=>({x:4,y:0,z:0,hp:100});
function solve(g){const events=g.pattern.map((direction,i)=>({id:i+1,direction}));return advanceStruggle(g,{struggle:events},g.minHold+.1);}
test('bigger arms require more taps and a longer wrap; repeated grabs vary their sequence and strength',()=>{const short={id:4,type:0,span:{length:3}},long={...short,span:{length:30}};const a=grabProfile(short),b=grabProfile(long);assert.ok(b.required>a.required);assert.ok(b.minHold>a.minHold);assert.ok(b.wrap>a.wrap);assert.ok(b.strength>a.strength);const p=player();beginGrab(p,long);const first=p.grab;releaseGrab(p,long);p.grabImmune=p.grabRecovery=0;beginGrab(p,long);assert.notDeepEqual(p.grab.pattern,first.pattern);assert.notEqual(p.grab.required,first.required);assert.match(strugglePrompt(p.grab),/[WASD]/);assert.match(strugglePrompt(p.grab,true),/[←→↑↓]/);});
test('ordered repeated taps survive packet batching, duplicate delivery cannot progress, holds cannot auto-mash',()=>{const p=player(),a={id:6,type:0,reach:5};beginGrab(p,a);const g=p.grab,pattern=[...g.pattern];let events=[],serial=0;for(let i=0;i<pattern.length;i++){events.push({id:++serial,direction:pattern[i]});advanceStruggle(g,{struggle:events},.12);const before=g.steps;advanceStruggle(g,{struggle:events},.01);assert.equal(g.steps,before);}assert.equal(g.steps,g.required);assert.ok(advanceStruggle(g,{struggle:events},3));beginGrab({hp:100},a);const q=player();beginGrab(q,{id:1,reach:3});for(let i=0;i<100;i++)advanceStruggle(q.grab,{forward:1},.02);assert.ok(q.grab.steps<=1);});
test('mistakes do not erase progress; a completed early mash waits for the wrapping pose',()=>{const p=player();beginGrab(p,{id:1,reach:30});const g=p.grab,events=g.pattern.map((direction,i)=>({id:i+1,direction}));for(let i=0;i<events.length;i+=4)advanceStruggle(g,{struggle:events.slice(i,i+4)},.01);assert.equal(g.steps,g.required);assert.ok(g.age<g.minHold);assert.equal(advanceStruggle(g,{struggle:[]},.01),false);assert.equal(advanceStruggle(g,{struggle:[]},g.minHold),true);});
test('all taps in a coalesced packet are applied in order without silently discarding the tail',()=>{const p=player();beginGrab(p,{id:8,reach:30});const g=p.grab;const events=g.pattern.map((direction,i)=>({id:i+1,direction}));assert.ok(events.length>8);assert.ok(advanceStruggle(g,{struggle:events},4));assert.equal(g.steps,g.required);});
test('controller flick edges match keyboard taps and malformed network inputs are discarded',()=>{const input=new StruggleInput();input.samplePad(-1,0);input.samplePad(-1,0);input.samplePad(0,0);input.samplePad(-1,0);assert.equal(input.events.length,2);assert.ok(input.events.every(e=>e.direction==='left'));const clean=sanitizeInput({seq:1,struggle:[...input.events,{id:Infinity,direction:'left'},{id:3,direction:'oops'}]});assert.deepEqual(clean.struggle,input.events);});
test('span stops at next wall or 30m; swept crossings catch fast players without reaching through walls or decks',()=>{const p={x:0,y:1.6,z:0,nx:1},wall={blocked:(x)=>x>=19};p.span=tentacleSpan(wall,p);assert.ok(p.span.length<19&&p.span.length>18);assert.equal(tentacleSpan({blocked:()=>false},p).length,30);p.extension=p.span.length;assert.ok(crossesTentacle(p,{x:12,y:0,z:1,tentaclePrevious:{x:12,y:1,z:-1}}));assert.equal(crossesTentacle(p,{x:22,y:0,z:0}),false);assert.equal(crossesTentacle(p,{x:10,y:4,z:0}),false);assert.equal(crossesTentacle(p,{x:10,y:0,z:5}),false);for(const ny of[-1,1]){const v={x:0,z:0,y:ny===1?.05:3.75,ny};v.span=tentacleSpan({blocked:(_x,y)=>y<=0||y>=3.8},v);v.extension=v.span.length;assert.ok(crossesTentacle(v,{x:.3,y:0,z:0}));}});
test('dragging is substepped and stops at solid obstacles or a missing floor',()=>{const p={...player(),x:10,grab:{strength:2}},world={floor:()=>0,canMove:x=>x>8};dragCaptive(world,p,{x:0,z:0},3);assert.ok(p.x>8&&p.x<8.11);const x=p.x;dragCaptive({...world,floor:()=>null},p,{x:0,z:0},2);assert.equal(p.x,x);});
test('all parasites telegraph, attack, attach once, and release on teammate kill or varied tap sequences',()=>{const world={floor:()=>0,canMove:()=>true,los:()=>true};for(const kind of PARASITES){const a=makeActor(kind,0,0),m={id:'peer',player:{...player(),x:1}};a.cooldown=0;const events=[];updateActor(a,.01,m.player,world,e=>events.push(e));assert.equal(a.state,'tell');updateActor(a,ACTORS[kind].windup+.01,m.player,world,e=>events.push(e));for(let i=0;i<20;i++)updateActor(a,.03,m.player,world,e=>{if(e.type==='latch')attachParasite(a,m);});assert.equal(a.attachedTo,m.id);assert.equal(m.player.grab.kind,kind);assert.equal(attachParasite(a,m),false);const system={world,patches:[]},pattern=m.player.grab.pattern;let taps=[];for(let i=0;i<pattern.length;i++){taps.push({id:i+1,direction:pattern[i]});tickTentacles(system,[m],.2,()=>({struggle:taps}),()=>{},[a]);}tickTentacles(system,[m],2,()=>({struggle:taps}),()=>{},[a]);assert.equal(m.player.grab,null);assert.equal(a.attachedTo,null);assert.equal(grabSheet(m.player),'escape-'+kind);assert.ok(m.player.grabRecovery>=0);m.player.grabRecovery=m.player.grabImmune=0;attachParasite(a,m);a.hp=0;tickTentacles(system,[m],.01,()=>({}),()=>{},[a]);assert.equal(m.player.grab,null);assert.equal(m.player.grabRelease,'destroyed');}});
test('all 28 character/attacker combinations use dedicated sheets, moving struggles and two release poses',()=>{for(const type of[0,1,2,3,...PARASITES]){const p=player(),kind=typeof type==='number'?'tentacle':type;beginGrab(p,{id:7,type,reach:5},kind);const sheet=grabSheet(p);assert.ok(SPECS[sheet]);assert.equal(SPECS[sheet].rows,4);assert.equal(SPECS[sheet].rects.flat().length,32);const frames=new Set();for(let i=0;i<20;i++){p.grab.age+=.1;frames.add(grabbedFrame(p));}assert.ok(frames.size>=5);releaseGrab(p);assert.equal(grabbedFrame(p),6);p.grabRecovery=.3;assert.equal(grabbedFrame(p),7);}});
test('new parasites actually occur in campaign encounters and retain all six enemy animation rows',()=>{const w=makeWorld(2709,2,2),plan=encounterPlan(w,2);for(const kind of PARASITES){assert.ok(plan.some(p=>p.type===kind));assert.equal(SPECS[kind].rects.flat().length,48);}});

test('facehugger keeps the victim in first person through release; other captures retain third person',()=>{for(const kind of ['tentacle',...PARASITES]){const p=player();beginGrab(p,{id:1,type:0,reach:4},kind);assert.equal(firstPersonGrab(p),kind==='facehugger');releaseGrab(p);assert.equal(firstPersonGrab(p),kind==='facehugger');p.grabRecovery=0;assert.equal(firstPersonGrab(p),false);}});

test('restored saves and departed captives cannot leave an invisible attached parasite',()=>{for(const members of [[],[{id:'peer',player:{hp:100,grab:null}}]]){const a={id:3,type:'burrower',hp:10,attachedTo:'peer',state:'attached',y:1};releaseOrphanParasites([a],members);assert.equal(a.attachedTo,null);assert.equal(a.state,'recover');assert.equal(a.y,0);}});
