import test from'node:test';import assert from'node:assert/strict';
import sharp from'sharp';import{readFile}from'node:fs/promises';import{packImage}from'../scripts/pack-image.mjs';
import{effectSprite,releaseEffectSprite,clearEffectPool,effectBeam,orientBeam}from'../src/pixel-effects.js';import{PLAYER_SHOTS,shotLight}from'../src/player-projectiles.js';import{CombatLights}from'../src/lighting.js';import*as THREE from'../vendor/three.module.js';
test('cartridge image encoding preserves every RGBA byte and dimensions without downsampling',async()=>{const source=await readFile(new URL('../assets/generated/player-projectiles-v11.png',import.meta.url));const packed=await packImage(source);assert.ok(packed.buffer.length<source.length);assert.equal(packed.mime,'image/webp');const before=await sharp(source).ensureAlpha().raw().toBuffer({resolveWithObject:true}),after=await sharp(packed.buffer).ensureAlpha().raw().toBuffer({resolveWithObject:true});assert.deepEqual(after.info,before.info);assert.ok(before.data.equals(after.data));});
test('effect sprites reuse bounded materials and reset prior gore, tint, opacity and transform state',()=>{clearEffectPool();const tex=new THREE.Texture(),atlas={frame:()=>0,texture:()=>tex},s=effectSprite(atlas,1,0,1,2,3,1);s.material.opacity=.2;s.material.rotation=2;s.material.depthWrite=true;s.center.set(.5,0);releaseEffectSprite(s);const reused=effectSprite(atlas,2,1,4,5,6,.7,'#ff0000');assert.equal(reused,s);assert.equal(reused.material.opacity,1);assert.equal(reused.material.rotation,0);assert.equal(reused.material.depthWrite,false);assert.equal(reused.material.fog,true);assert.deepEqual(reused.center.toArray(),[.5,.5]);assert.deepEqual(reused.position.toArray(),[4,5,6]);releaseEffectSprite(reused);clearEffectPool();});
test('every weapon has its own animated projectile and moving light, with a fixed ten-light pool',()=>{assert.equal(Object.keys(PLAYER_SHOTS).length,7);assert.equal(new Set(Object.values(PLAYER_SHOTS).map(s=>s.row)).size,7);const lights=new CombatLights(new THREE.Scene()),effect={gun:'arc',age:.07,mesh:{position:new THREE.Vector3(1,2,3)}},first=shotLight(effect);lights.update(.1,[],[first]);assert.ok(lights.snapshot().some(l=>l.kind==='player-arc'));effect.mesh.position.x=8;const next=shotLight(effect);lights.update(.1,[],[next]);assert.equal(lights.lights[5].light.position.x,8);assert.equal(lights.lights.length,10);lights.update(.1);assert.equal(lights.snapshot().length,0);});
test('beam facing updates reuse the vertex buffer while retaining the exact endpoints',()=>{const atlas={frame:()=>0,texture:()=>new THREE.Texture()},camera=new THREE.PerspectiveCamera();camera.position.set(1,2,3);const beam=effectBeam(atlas,{x:0,y:0,z:0},{x:0,y:0,z:-5},'#fff',.4,camera),array=beam.geometry.attributes.position.array;camera.position.x=3;orientBeam(beam,camera);assert.equal(beam.geometry.attributes.position.array,array);assert.ok([...array].every(Number.isFinite));assert.equal((array[2]+array[5])/2,0);assert.equal((array[8]+array[11])/2,-5);beam.geometry.dispose();beam.material.dispose();});

test('smaller ZIP distribution unpacks to byte-identical HTML and carries a valid central directory',async()=>{const{zipCartridge}=await import('../scripts/zip-cartridge.mjs'),{mkdtemp,writeFile,rm}=await import('node:fs/promises'),{tmpdir}=await import('node:os'),{join}=await import('node:path'),{inflateRawSync}=await import('node:zlib');const dir=await mkdtemp(join(tmpdir(),'scrapper-zip-'));try{const html=Buffer.from('<html>pixel art, gameplay, all assets</html>\n'.repeat(400)),input=join(dir,'Scrapper.html'),out=join(dir,'Scrapper.zip');await writeFile(input,html);const result=await zipCartridge(input,out),zip=await readFile(out),start=30+zip.readUInt16LE(26),end=zip.length-22,central=zip.readUInt32LE(end+16),compressed=zip.readUInt32LE(central+20);assert.equal(zip.readUInt32LE(end),0x06054b50);assert.ok(inflateRawSync(zip.subarray(start,start+compressed)).equals(html));assert.ok(result.bytes<html.length);assert.equal(zip.readUInt32LE(central+24),html.length);}finally{await rm(dir,{recursive:true,force:true});}});
