import test from'node:test';import assert from'node:assert/strict';
import{makeWorld}from'../src/world.js';import{CHAPTERS}from'../src/campaign.js';import{MissionTasks}from'../src/mission-tasks.js';import{Infestation}from'../src/infestation.js';import{installStationProps,stationPropPlan,STATION_PROPS,clearStationOverlap}from'../src/station-props.js';import{RouteGuide}from'../src/navigation.js';import{movePlayer}from'../src/traversal.js';import{renderSound}from'../src/audio.js';
function prepare(chapter,seed=2709+chapter*911){const w=makeWorld(seed,CHAPTERS[chapter].theme,chapter),tasks=new MissionTasks(w,chapter),growth=new Infestation(w),reserved=[...tasks.nodes,...growth.patches];return{w,tasks,reserved};}
test('station dressing reproduces between hosts and saves without consuming combat RNG or duplicating colliders',()=>{
 const a=prepare(0),b=prepare(0);const plan=stationPropPlan(a.w,a.reserved);assert.deepEqual(plan,stationPropPlan(b.w,b.reserved));assert.equal(a.w.random(),b.w.random());installStationProps(a.w,a.reserved);const count=a.w.obstacles.length;installStationProps(a.w,a.reserved);assert.equal(a.w.obstacles.length,count);assert.deepEqual(a.w.stationProps,plan);assert.equal(new Set(plan.map(p=>p.id)).size,plan.length);
});
test('all chapters have dense varied dressing, low-ceiling clearance and accessible mission routes',()=>{
 for(let chapter=0;chapter<12;chapter++)for(const seed of[2709+chapter*911,71]){const{w,tasks,reserved}=prepare(chapter,seed);const reachableSupplies=w.supplies.filter(n=>w.waypoint(w.start.x,w.start.z,n.x,n.z,{startY:w.start.y,endY:n.y,ignoreGates:true}));w.waypoint(w.start.x,w.start.z,w.control.x,w.control.z,{startY:w.start.y,endY:w.control.y});const props=installStationProps(w,reserved),types=new Set(props.map(p=>p.kind));assert.ok(props.length>280,chapter+'/'+seed);assert.ok(types.size>=36);assert.ok(props.filter(p=>p.room==='passage'||p.room.includes('service')||p.room.includes('conduit')).length>60);for(const kind of['pump','panel','lifeSupport','compactor','steamVent'])assert.ok(types.has(kind));for(const p of props){assert.ok(p.y+p.mount+p.h<p.ceiling);assert.ok(w.at(p.x+p.nx,p.z+p.nz,p.y));assert.equal(w.at(p.x-p.nx*1.1,p.z-p.nz*1.1,p.y),undefined);}
 for(const n of[...tasks.nodes,w.control,w.accessCard,w.exit,...w.cases,...reachableSupplies]){assert.ok(w.canMove(n.x,n.z,.3,n.y??0),`blocked interaction ${chapter}/${seed}/${n.id||n.gun}`);assert.ok(w.waypoint(w.start.x,w.start.z,n.x,n.z,{startY:w.start.y,endY:n.y,fullPath:true,ignoreGates:true}),`no path ${chapter}/${seed}/${n.id||n.gun}`);}}
});
test('real player motion follows the compass through installed machinery to every chapter objective and upper service deck',()=>{
 for(let chapter=0;chapter<12;chapter++){const{w,reserved}=prepare(chapter);installStationProps(w,reserved);for(const goal of[w.control,w.overpass.goal]){const p={...w.start,yaw:0,grounded:true,vy:0,safe:{...w.start}},g=new RouteGuide(w);let arrived=false;for(let i=0;i<6000;i++){g.update(p,goal,1/30);if(Math.hypot(p.x-goal.x,p.z-goal.z)<2&&Math.abs(p.y-goal.y)<.6){arrived=true;break;}assert.ok(g.next);p.yaw+=g.relative;w.tick(1/30,p);movePlayer(p,w,1/30,{forward:g.action.startsWith('WAIT')||g.action.startsWith('RIDE')?0:1});}assert.ok(arrived,`${chapter}: ${JSON.stringify({p,next:g.next,action:g.action})}`);}}
});
test('new spatial machinery sounds have finite samples, audible body, headroom and a smooth tail',()=>{
 for(const id of['steam','air','machine','compactor']){const data=renderSound(id,27),peak=Math.max(...data.map(Math.abs)),rms=Math.sqrt(data.reduce((a,n)=>a+n*n,0)/data.length);assert.ok(data.every(Number.isFinite));assert.ok(peak>.05&&peak<.8,id);assert.ok(rms>.008,id);assert.ok(Math.abs(data.at(-1))<.006,id);}
});

test('older saves inside newly placed equipment move clear without changing health or floor',()=>{
 const{w,reserved}=prepare(0);installStationProps(w,reserved);const o=w.obstacles.find(o=>o.stationProp),p={x:o.x,z:o.z,y:o.y,hp:61},savedY=p.y;assert.equal(w.canMove(p.x,p.z,.3,p.y),false);assert.ok(clearStationOverlap(w,p));assert.ok(w.canMove(p.x,p.z,.3,p.y));assert.equal(p.y,savedY);assert.equal(p.hp,61);const after={...p};assert.equal(clearStationOverlap(w,p),false);assert.deepEqual(p,after);
});

test('each map theme includes static mounted pipes, cables, consoles and scientific instruments without per-object animation',()=>{
 for(let theme=0;theme<4;theme++){const w=makeWorld(71,theme,theme),props=stationPropPlan(w),dressed=props.filter(p=>STATION_PROPS[p.kind].static);assert.ok(dressed.length>60);const kinds=new Set(dressed.map(p=>p.kind.split('-').slice(1).join('-')));for(const kind of ['pipes','cableTray','ceilingRack','console','analyzer','specimen'])assert.ok(kinds.has(kind),theme+'/'+kind);
 for(const p of dressed){const d=STATION_PROPS[p.kind];assert.equal(d.frames,1);assert.equal(d.billboard,undefined);assert.ok(p.y+p.mount+p.h<p.ceiling);assert.ok(w.at(p.x+p.nx,p.z+p.nz,p.y));if(d.detail)assert.equal(d.depth,0);}}
});
