import test from'node:test';import assert from'node:assert/strict';import{readFileSync}from'node:fs';import{createHash}from'node:crypto';
import{SPECS}from'../src/atlas.js';import{wipeMotion,VisorState}from'../src/visor.js';import{Radio,POWER,initialMission,applyDecision}from'../src/comms.js';import{CHAPTERS,storyMessage,recoveryJournal,campaignEnding,previousRecovery}from'../src/campaign.js';
test('restored visor sheet is the four original single-glove poses',()=>{assert.equal(SPECS.wipe.path,'assets/legacy/visor-wipe.png');assert.equal(SPECS.wipe.cols,4);assert.equal(SPECS.wipe.rows,1);const png=readFileSync(new URL('../'+SPECS.wipe.path,import.meta.url));assert.equal(createHash('sha256').update(png).digest('hex'),'3f0821d459c75484c6ca2e368cae8606789d463aa0ed1650478ec6c6a810c746');assert.equal(png.readUInt32BE(16),2048);assert.equal(png.readUInt32BE(20),768);});
test('one hand sweeps monotonically once; gun is completely lowered while that hand is visible',()=>{let last=Infinity,lastEdge=1;const frames=new Set();for(let i=0;i<=1000;i++){const p=wipeMotion(i/1000);assert.ok(p.clearEdge<=lastEdge);lastEdge=p.clearEdge;if(p.visible){assert.equal(p.gunDrop,1);assert.ok(p.x<=last);last=p.x;frames.add(p.frame);}}assert.equal(frames.size,4);assert.equal(wipeMotion(0).gunDrop,0);assert.equal(wipeMotion(1).gunDrop,0);assert.equal(lastEdge,0);});
test('a clean visor uses a clean glove, while the wipe keeps every captured blood color',()=>{const a=new VisorState();a.wipe();assert.deepEqual(a.palette,[]);const b=new VisorState();for(const c of['green','cyan','amber','violet','oil'])b.stain(.5,true,c);b.wipe();assert.equal(b.palette.length,5);for(let i=0;i<70;i++)b.update(1/60);assert.equal(b.stains.length,0);assert.equal(b.active,null);});
test('field logs survive new progress messages and a decision resumes the interrupted log at its prior time',()=>{const r=new Radio(),m=initialMission();r.send({id:'intro',text:'The original field log.',priority:true});r.update(2);r.send({id:'discovery',text:'Recovered evidence.',priority:true});assert.equal(r.active.id,'intro');r.send(POWER);assert.equal(r.active.id,'power');assert.ok(r.choose(1,m).accepted);assert.equal(r.active.id,'intro');assert.equal(r.elapsed,2);r.update(20);assert.equal(r.active.id,'discovery');r.update(20);assert.equal(r.active,null);assert.deepEqual(r.history.map(m=>m.id),['intro','power','discovery']);assert.equal(r.send({id:'intro',text:'Duplicate'}),false);});
test('all twelve case files have distinct evidence and unlock it only when the archive is actually recovered',()=>{assert.equal(new Set(CHAPTERS.map(c=>c.title)).size,12);assert.equal(CHAPTERS[0].title,'A Routine Recovery');assert.equal(new Set(CHAPTERS.map(c=>c.evidence)).size,12);for(let i=0;i<12;i++){const c=CHAPTERS[i],locked=recoveryJournal(i).join(' '),open=recoveryJournal(i,{mission:{record:true,choices:[]}}).join(' ');assert.ok(!locked.includes(c.evidence));assert.ok(open.includes(c.evidence));assert.ok(open.split(/\s+/).length>190);for(const k of['system','aftermath','preserve','purge','secret']){assert.ok(c[k].length>60);assert.ok(c[k].length<200);assert.equal(storyMessage(i,k).text,c[k]);}}});
test('previous recovery, journal consequences and endings follow actual choices without counting duplicate chapters',()=>{const r=(chapter,value,power='armory')=>({chapter,choices:[{id:'purge',value},{id:'power',value:power}]});assert.equal(previousRecovery(4,[r(7,'purge'),r(2,'preserve'),r(1,'purge')]).chapter,2);const p=storyMessage(3,'intro',{results:[r(2,'preserve')]}).text,q=storyMessage(3,'intro',{results:[r(2,'purge')]}).text;assert.notEqual(p,q);assert.match(p,/still has/);assert.match(q,/missing research/);const j=recoveryJournal(2,{mission:{record:true,...r(2,'purge','maintenance')}}).join(' ');assert.ok(j.includes(CHAPTERS[2].purge));assert.match(j,/Maintenance circuit committed/);const kept=Array.from({length:12},(_,i)=>r(i,'preserve','maintenance')),burned=Array.from({length:12},(_,i)=>r(i,'purge'));assert.notEqual(campaignEnding(kept),campaignEnding(burned));assert.match(campaignEnding(kept),/crew’s names remain attached/);assert.match(campaignEnding([]),/still need to be recovered/);assert.equal(campaignEnding(kept),campaignEnding([...kept,kept[0]]));});

test('purging before collecting the ledger records the order and never claims it was copied first',()=>{const mission=initialMission();applyDecision(mission,'purge','purge');assert.equal(mission.purgeBeforeRecord,true);assert.match(storyMessage(1,'purge',{mission}).text,/before I copied/);mission.record=true;const journal=recoveryJournal(1,{mission}).join(' ');assert.match(journal,/before I copied/);const completed={chapter:1,choices:mission.choices,purgeBeforeRecord:true};assert.match(recoveryJournal(1,{results:[completed]}).join(' '),/before I copied/);});
