import test from'node:test';import assert from'node:assert/strict';
import{tickTentacles,GRAB_DURATION,ESCAPE_STEPS,tentacleFrame}from'../src/tentacles.js';
import{devicePresentation}from'../src/task-visuals.js';
import{makeActor,updateActor,hurtActor}from'../src/combat.js';
import{surfaceIndex,wallSpans,uniqueCells}from'../src/world-surfaces.js';
import{makeWorld}from'../src/world.js';import{MissionTasks}from'../src/mission-tasks.js';import{installDeviceBodies}from'../src/device-placement.js';import{installStationProps}from'../src/station-props.js';import{Infestation}from'../src/infestation.js';
function fixture(type=0,surface='wall'){const patch={id:1,x:0,z:0,y:surface==='ceiling'?3.6:surface==='floor'?.05:1,reach:4,type,surface,maturity:1,hp:50,age:0,tentacleAge:0},member={id:'a',player:{x:1,z:0,y:0,hp:100}},system={patches:[patch],world:{los:()=>true}};return{patch,member,system};}
test('every strain and mounting surface warns before grabbing, then accepts alternating movement',()=>{for(let type=0;type<4;type++)for(const surface of['wall','floor','ceiling']){const{patch,member,system}=fixture(type,surface);tickTentacles(system,[member],.01);assert.equal(patch.tentacleState,'windup');assert.equal(member.player.grab,undefined);tickTentacles(system,[member],.86);assert.ok(member.player.grab);for(let i=0;i<ESCAPE_STEPS;i++)tickTentacles(system,[member],.12,()=>({strafe:i%2?1:-1}));assert.equal(member.player.grab,null);assert.equal(member.player.grabRelease,'escaped');assert.ok(patch.grabCooldown>7);assert.ok(member.player.grabImmune>2);}});
test('holding one key does not rapidly escape, timeout is bounded, and walls or dodging defeat a strike',()=>{let f=fixture();tickTentacles(f.system,[f.member],.01);tickTentacles(f.system,[f.member],.9);for(let i=0;i<10;i++)tickTentacles(f.system,[f.member],.1,()=>({forward:1}));assert.equal(f.member.player.grab.steps,1);tickTentacles(f.system,[f.member],GRAB_DURATION);assert.equal(f.member.player.grab,null);f=fixture();f.system.world.los=()=>false;tickTentacles(f.system,[f.member],1);assert.equal(f.member.player.grab,undefined);f=fixture();tickTentacles(f.system,[f.member],.01);f.member.player.x=10;tickTentacles(f.system,[f.member],1);assert.equal(f.patch.tentacleState,'recoil');assert.equal(f.member.player.grab,undefined);});
test('destroyed colonies free a co-op captive; snapshots preserve an in-progress struggle',()=>{const{patch,member,system}=fixture();tickTentacles(system,[member],.01);tickTentacles(system,[member],1);const copy=JSON.parse(JSON.stringify({patch,member}));assert.deepEqual(copy.member.player.grab,member.player.grab);patch.dead=true;tickTentacles(system,[member],.01);assert.equal(member.player.grab,null);assert.equal(member.player.grabRelease,'destroyed');for(const[deathAge,expected]of[[0,5],[.3,6],[1,7]])assert.equal(tentacleFrame({...patch,deathAge}),expected);});
test('bosses and mini bosses remember a sensed player beyond normal acquisition range',()=>{for(const type of['matriarch','guardian','marshal']){let sight=true,paths=0;const world={floor:()=>0,los:()=>sight,canMove:()=>true,waypoint:()=>{paths++;return{x:50,z:0};}},a=makeActor(type,0,0);updateActor(a,.1,{x:10,z:0,y:0},world,()=>{});assert.equal(a.hunting,true);sight=false;const x=a.x;updateActor(a,.1,{x:60,z:0,y:0},world,()=>{});assert.ok(a.x>x);assert.ok(paths>0);}const a=makeActor('beetle',0,0);updateActor(a,1,{x:100,z:0,y:0},{floor:()=>0,los:()=>{throw Error('unnecessary distant sight test');}},()=>{});assert.equal(a.state,'idle');});
test('vertical neighbours and stair risers cannot create see-through wall intervals',()=>{const c={x:0,z:0,y:0,ceiling:3.8},upper={x:1,z:0,y:6,ceiling:9.8};let spans=wallSpans(c,1,0,surfaceIndex([c,upper]));assert.equal(spans.length,4);assert.ok(spans.every(s=>s.low===0&&s.high===3.8));const next={...upper,y:1,ceiling:3};spans=wallSpans(c,1,0,surfaceIndex([c,next]));assert.equal(spans.length,8);assert.ok(spans.every(s=>s.high<=1||s.low>=3));assert.equal(uniqueCells([c,{...c}]).length,1);});
test('all chapters keep solid devices reachable and eliminate shallow overlapping stair decks',()=>{for(let chapter=0;chapter<12;chapter++){const w=makeWorld(2709+chapter*911,chapter%4,chapter);installDeviceBodies(w,[w.control,w.purge,...w.switches.filter(s=>s.timedGate||w.puzzle.required!==false)]);const tasks=new MissionTasks(w,chapter);installDeviceBodies(w,tasks.nodes);const infestation=new Infestation(w);for(const p of infestation.patches.filter(p=>p.surface==='ceiling'))assert.ok(p.reach>p.y-p.floor-.9,'ceiling hook reaches standing players');installStationProps(w,[...tasks.nodes,...infestation.patches]);assert.ok(w.renderCells().every(c=>c.ceiling-c.y>=1.8));const decks=[...surfaceIndex(w.renderCells()).values()].find(list=>list.length>1).sort((a,b)=>a.y-b.y),x=decks[0].x*2+1,z=decks[0].z*2+1;assert.equal(w.los(x,z,x,z,decks[0].y+1,decks[1].y+1),false,'vertical sight cannot cross a deck');assert.ok(tasks.nodes.filter(n=>!n.plate&&n.kind!=='coupler'&&!n.action?.startsWith('sample-')).every(n=>n.body));for(const n of tasks.nodes){assert.ok(w.canMove(n.x,n.z,.3,n.y),`${chapter}/${n.id} approach`);if(n.body)assert.equal(w.canMove(n.body.x,n.body.z,.2,n.y),false);assert.ok(w.waypoint(w.start.x,w.start.z,n.x,n.z,{startY:w.start.y,endY:n.y,ignoreGates:true}),`${chapter}/${n.id} path`);}}});

test('inactive solid equipment stays visible and collectible samples never leave hidden colliders',()=>{const tasks={visible:()=>false};assert.deepEqual(devicePresentation(tasks,{body:{}}),{visible:true,readout:false});assert.deepEqual(devicePresentation(tasks,{kind:'coupler'}),{visible:false,readout:false});const world={obstacles:[],canMove:()=>true,floor:()=>0},sample={id:'sample',action:'sample-0',x:0,z:0,y:0};installDeviceBodies(world,[sample]);assert.equal(sample.body,undefined);assert.equal(world.obstacles.length,0);});
