import * as THREE from '../vendor/three.module.js';
import {Atlas,THEMES} from './atlas.js';
import {ACTORS,WEAPONS,WEAPON_BY_ID,PILOTS,SPEAKERS} from './catalog.js';
import {makeWorld,TILE} from './world.js';
import {Arsenal,makeActor,makeNest,damageNest,updateNest,hurtActor,updateActor,aimDirection,raySphere} from './combat.js';
import {Radio,POWER,PURGE,initialMission} from './comms.js';
import {VisorState} from './visor.js';
import {LevelVisuals} from './level-renderer.js';
import {movePlayer} from './traversal.js';
import {CHAPTERS,storyMessage,campaignEnding,recoveryJournal} from './campaign.js';
import {rollLoot,nextOwnedWeapon} from './loot.js';
import {installChrome,helmetPortrait,drawDashboard} from './hud-art.js';
import {effectSprite,effectRing,effectBeam,orientBeam,areaEffect,animateArea} from './pixel-effects.js';
import {Infestation,GROWTH_COLORS,GROWTH_GOO} from './infestation.js';
import {InfestationVisuals} from './infestation-visuals.js';
import {installStationProps,clearStationOverlap} from './station-props.js';
import {StationVisuals} from './station-visuals.js';
import {SoundStage} from './audio.js';
import {NetRoom} from './network.js';
import {directionalFrame,hitPlayer,canHurtPlayer,updateRevives,respawnPoint} from './crew.js';
import {SPECS} from './atlas.js';
import {CampaignStore} from './campaign-save.js';
import {encounterPlan,INTRODUCTIONS} from './encounters.js';
import {MissionTasks} from './mission-tasks.js';
import {RouteGuide} from './navigation.js';
import {CompassContacts,CompassView,compassTargets} from './compass.js';
import {CombatLights} from './lighting.js';
import {TaskVisuals} from './task-visuals.js';
import {ControllerInput,PAD,lookDelta,controllerSettings} from './controller.js';
import {ControllerMenu} from './controller-menu.js';

const $=id=>document.getElementById(id),view=$('view'),overlay=$('overlay'),ctx=overlay.getContext('2d');
let storedController;try{storedController=JSON.parse(localStorage.getItem('scrapper-controller'));}catch{}
const controller=new ControllerInput(storedController),controllerMenu=new ControllerMenu();let inputDevice='mouse',controllerContext='';
const compassView=new CompassView($('compass-scale'),$('compass-contacts'));
const renderer=new THREE.WebGLRenderer({canvas:view,antialias:false});
renderer.setPixelRatio(Math.min(devicePixelRatio,1.5));
const camera=new THREE.PerspectiveCamera(76,innerWidth/innerHeight,.07,180);camera.rotation.order='YXZ';
let scene,architecture,world,actors=[],nests=[],cases=[],pickups=[],effects=[],projectiles=[],waves=[],decorations=[];
let player,arsenal,visor,radio,mission,pilot='rook',themeIndex=0,ready=false,running=false,paused=false;
let elapsed=0,recoil=0,damageFlash=0,hitTime=0,toastTime=0,shake=0,bob=0,shooting=false,wipePose=null,radioId=null,ending=false;
let recordTerminal,exitDoor,purgeTerminal,bridgeAdded=false,campaign=[];
let decals=[],levelVisuals,infestation,growthVisuals,stationVisuals,chapterIndex=0,score=0,entryScore=0,entryLoadout=null,storyEvents=new Set(),mapOpen=false,wheelCooldown=0;
const GORE_ROWS={beetle:0,spitter:0,shardling:0,crawler:1,splitter:1,lancer:1,bomber:7,tank:2,warden:2,guardian:6,matriarch:6,priest:3,bat:3,leech:3,marshal:4,worm:4,jelly:5,scorpion:6,drone:7,spider:7,parallax:7,overseer:3};
const GORE=Object.fromEntries(Object.entries(ACTORS).map(([id,d])=>[id,{color:d.blood,ink:{cyan:'#55ced9',amber:'#e7b647',green:'#9ebd54',violet:'#bd83e8',oil:'#f1a552'}[d.blood],row:d.blood==='oil'?3:d.blood==='violet'?2:d.blood==='amber'?1:0}]));
const keys=new Set(),atlas=new Atlas(),sfx=new SoundStage();let pendingShots=[],stepTimer=0;
let crew=[],activeMember=null,mode='solo',tasks,taskVisuals,guide,compass,lights,baseSeed=2709,saveTimer=0,netEvents=[],eventSerial=0,lastEvent=0,projectileSerial=0,matchTime=0;
const net=new NetRoom(networkEvent),saves=new CampaignStore();
function toast(text){if(activeMember&&activeMember.id!==net.self){activeMember.notice={text,id:++eventSerial};return;}$('toast').textContent=text;toastTime=3.8;}
function billboard(canvas,x,z,size=2,y=0){const mat=new THREE.SpriteMaterial({map:atlas.texture(canvas),transparent:true,alphaTest:.22,depthWrite:true,fog:true});const sprite=new THREE.Sprite(mat);sprite.center.set(.5,0);sprite.position.set(x,y,z);sprite.scale.set(size,size,1);scene.add(sprite);return sprite;}
function changeFrame(sprite,canvas){const map=atlas.texture(canvas);if(sprite.material.map!==map){sprite.material.map=map;sprite.material.needsUpdate=true;}}
function disposeWorld(){if(!scene)return;scene.traverse(o=>{if(o.isMesh)o.geometry?.dispose();if(o.material&&!Array.isArray(o.material))o.material.dispose();});}

function buildArchitecture(){
 if(levelVisuals){scene.remove(levelVisuals.group);levelVisuals.dispose();}
 levelVisuals=new LevelVisuals(world,atlas,themeIndex);architecture=levelVisuals.group;scene.add(architecture);
}
function objectBox(point,tileIndex,width,height,depth){const tile=atlas.frame('env-'+THEMES[themeIndex].id,tileIndex%4,Math.floor(tileIndex/4));const box=new THREE.Mesh(new THREE.BoxGeometry(width,height,depth),new THREE.MeshLambertMaterial({map:atlas.texture(tile),color:'#d2dcdf'}));box.position.set(point.x,(point.y??world.floor(point.x,point.z)??0)+height/2,point.z);scene.add(box);return box;}
function spawnActor(id,x,z,finalBrood=false,feetY){if(actors.filter(a=>a.hp>0).length>=(mode==='coop'?Math.max(1,net.members.length)*160:200))return null;const a=makeActor(id,x,z);a.groundY=world.floor(x,z,feetY)??feetY??0;a.sprite=billboard(atlas.actor(id,'idle',0),x,z,ACTORS[id].size,a.groundY);actors.push(a);return a;}
function addPickup(kind,id,x,z,delay=0,amount=0){
 const index=kind==='health'||kind==='scrap'?7:WEAPON_BY_ID[id].index,row=kind==='ammo'?1:0,y=world.floor(x,z)??0;
 const p={kind,gun:id,x,z,y,age:0,delay,amount,taken:false};
 p.sprite=billboard(atlas.frame('pickups',index,row),x,z,kind==='gun'?1.65:1.05,y+.18);
 if(kind==='scrap'){changeFrame(p.sprite,atlas.frame('oldLoot',3,1));p.sprite.material.color.set('#efbd70');}
 if(kind==='health')changeFrame(p.sprite,atlas.frame('oldLoot',0,2));pickups.push(p);return p;
}
function setup(seed=2709,index=0,keep=false,layoutVersion=3){
 const retained=keep?arsenal:null;sfx.stopAll();pendingShots=[];stepTimer=0;disposeWorld();baseSeed=seed;chapterIndex=index%CHAPTERS.length;mode=net.active?net.mode:'solo';const chapter=CHAPTERS[chapterIndex];themeIndex=chapter.theme;const theme=THEMES[themeIndex];world=makeWorld(seed+chapterIndex*911,themeIndex,layoutVersion===3?chapterIndex:null);
 scene=new THREE.Scene();scene.background=new THREE.Color(theme.fog);scene.fog=new THREE.Fog(theme.fog,45,145);architecture=null;levelVisuals=null;lights=new CombatLights(scene);buildArchitecture();
 player={...world.start,vy:0,yaw:0,pitch:0,hp:100,grounded:true,safe:{...world.start},hurtCooldown:0};arsenal=retained||new Arsenal();visor=new VisorState();radio=new Radio();mission=initialMission();actors=[];nests=[];cases=[];pickups=[];effects=[];projectiles=[];waves=[];bridgeAdded=false;ending=false;radioId=null;elapsed=0;storyEvents=new Set();mapOpen=false;score=keep?score:entryScore;netEvents=[];lastEvent=eventSerial=0;matchTime=0;saveTimer=0;toastTime=0;tasks=new MissionTasks(world,chapterIndex);guide=new RouteGuide(world);compass=new CompassContacts(world);taskVisuals=new TaskVisuals(scene,tasks,atlas,levelVisuals);
 if(!keep&&entryLoadout){arsenal.slots=structuredClone(entryLoadout.slots);arsenal.selected=entryLoadout.selected;}
 infestation=new Infestation(world,{enabled:mode!=='ffa'});growthVisuals=new InfestationVisuals(scene,infestation,atlas);
 stationVisuals=new StationVisuals(scene,installStationProps(world,[...tasks.nodes,...infestation.patches]),atlas);stationVisuals.update(0,player,null,world);
 entryScore=score;entryLoadout={slots:structuredClone(arsenal.slots),selected:arsenal.selected};
 const previous=campaign.at(-1),purgedBefore=previous?.choices.some(c=>c.id==='purge'&&c.value==='purge');
 for(const p of mode==='ffa'?[]:world.nests){const n=makeNest(p.x,p.z);n.y=p.y;n.variant=p.variant;n.budget=purgedBefore?3:5;n.sprite=billboard(nestFrame(n),n.x,n.z,n.variant===2?3.45:2.9,n.y);nests.push(n);}
 if(mode!=='ffa'){const machine=makeNest(world.fabricator.x,world.fabricator.z,true);machine.y=world.fabricator.y;machine.budget=4;machine.sprite=billboard(atlas.frame('legacyProps',0,0),machine.x,machine.z,3,machine.y);nests.push(machine);}
 decorations=[];for(const r of world.rooms){if(r.id==='arrival'){for(const dx of[-7,7]){const sprite=billboard(atlas.frame('legacyProps',0,5),r.center.x+dx,r.center.z,3,r.y);decorations.push({sprite,row:5});}}else if(r.id==='east'||r.id==='upper'){const sprite=billboard(atlas.frame('legacyProps',0,1),r.center.x+10,r.center.z+7,3,r.y);decorations.push({sprite,row:1});}}
 for(const c of world.cases){const b={...c,open:false,age:0,dispensed:false};b.sprite=billboard(atlas.frame('pickups',0,2),b.x,b.z,2.5,b.y);cases.push(b);}
 for(const p of world.supplies)addPickup(p.kind,p.gun,p.x,p.z,0,p.amount||0);
 addPickup('ammo','bolt',world.start.x-6,world.start.z-10);
 for(const e of encounterPlan(world,chapterIndex,net.members.length||1,mode))spawnActor(e.type,e.x,e.z,false,e.y);
 if(previous&&!purgedBefore&&mode!=='ffa'){const r=world.rooms.find(r=>r.id==='hall');spawnActor('beetle',r.center.x+9,r.center.z+5);spawnActor('spitter',r.center.x-9,r.center.z-5);}
 recordTerminal=objectBox(world.control,12,1.8,2.2,.7);purgeTerminal=objectBox(world.purge,12,1.7,2.1,.65);exitDoor=objectBox(world.exit,8,4,3.7,.35);
 for(const [point,text]of [[world.control,'RECOVERY ARCHIVE\nACCESS RECORD'],[world.purge,'RESEARCH BANK\nARCHIVE CONTROL']]){const screen=levelVisuals.terminal(text,point.x,point.y+1.35,point.z+.36,1.5);scene.add(screen);}
 $('sector-name').textContent=String(chapterIndex+1).padStart(2,'0')+' / '+chapter.title.toUpperCase();$('theme').value=chapterIndex;$('pilot-name').textContent=PILOTS[pilot].name.toUpperCase();
 decals=[];initializeCrew(keep);if(mode==='ffa'){for(const g of world.gates)g.open=true;for(const c of cases)c.locked=false;for(const r of world.rooms)addPickup('health',null,r.center.x,r.center.z,0,35);}
 camera.position.set(player.x,player.y+1.65,player.z);camera.rotation.set(0,0,0);drawHud();
}
function nestFrame(n){
 if(n.variant===1)return atlas.frame('legacyProps',Math.floor(n.age*6)%4,2);
 if(n.variant===2)return atlas.frame('legacyProps',Math.floor(n.age*6)%4,3);
 const row=n.state==='husk'?3:n.state==='rupture'?2:n.state==='spawn'?1:0,col=n.state==='husk'?7:n.state==='rupture'?Math.min(7,Math.floor(n.age/.9*8)):Math.floor(n.age*8)%8;return atlas.frame('pod',col,row);
}
function story(event){if(storyEvents.has(event))return;storyEvents.add(event);radio.send({...storyMessage(chapterIndex,event,{results:campaign,mission}),priority:true});}

function particleBurst(x,y,z,color,count=24,power=4){emitVisual('particles',{x,y,z,color,count,power});if(count>20)lights?.flash({x,y,z},color,6,.3,13);
 for(let i=0;i<Math.ceil(count*.62);i++){const size=.17+world.random()*.3,mesh=effectSprite(atlas,7,Math.floor(world.random()*8),x,y,z,size,color);mesh.material.rotation=world.random()*Math.PI*2;scene.add(mesh);effects.push({mesh,life:.45+world.random()*.65,age:0,vfx:7,offset:i%8,vx:(world.random()-.5)*power,vy:world.random()*power*.9,vz:(world.random()-.5)*power,gravity:7});}
 while(effects.length>320)removeEffect(effects.shift());
}
function ring(x,z,color,max=6,duration=.7,y=.05){emitVisual('ring',{x,z,color,max,duration,y});const ground=world.floor(x,z)??0,area=max>=3,row=color.includes('c4')||color.includes('ba')||color.includes('d8')?3:color.includes('ad')||color.includes('b5')?1:2,mesh=area?areaEffect(atlas,x,ground+y,z,color,row):effectRing(atlas,x,ground+y,z,color);scene.add(mesh);lights?.flash({x,y:ground+1,z},color,11,duration,12);effects.push({mesh,age:0,life:duration,ring:true,vfx:area?undefined:4,max,area,color});}
function beam(from,to,color,life=.14,width=.035){emitVisual('beam',{from:{x:from.x,y:from.y,z:from.z},to:{x:to.x,y:to.y,z:to.z},color,life,width});lights?.flash(from,color,8,life,16);lights?.flash(to,color,4,life,9);const mesh=effectBeam(atlas,from,to,color,Math.max(.09,width*5),camera);scene.add(mesh);effects.push({mesh,life,age:0,vfx:5});}
function removeEffect(e){scene.remove(e.mesh);e.mesh.traverse(o=>{o.geometry?.dispose();o.material?.dispose();});}
function damageGrowth(p,damage,flame=false){
 const alive=!p.dead;infestation.hit(p.id,damage,flame);if(!alive)return;
 particleBurst(p.x+p.nx*.2,p.y,p.z+p.nz*.2,GROWTH_COLORS[p.type],p.dead?26:6,p.dead?5:2);
 if(p.dead){spriteBurst(p.x+p.nx*.3,p.y,p.z+p.nz*.3,p.type===3?1:p.type===2?2:0,2.2);floorSplatter(p.x+p.nx*.7,p.z+p.nz*.7,GROWTH_GOO[p.type],2);sfx.play(flame?'explosion':'acid',{position:p,gain:.55});if(Math.hypot(player.x-p.x,player.z-p.z)<4)visor.stain(world.random()*999,true,GROWTH_GOO[p.type]);}
 growthVisuals.update();
}
function updateWaveVisual(w){if(w.age<0)return;if(!w.mesh){w.mesh=areaEffect(atlas,w.x,w.y+.08,w.z,w.color,w.row??2);scene.add(w.mesh);}animateArea(w.mesh,atlas,w.radius,w.age,Math.min(1,(10.5-w.radius)/1.5));}
function updateLights(dt){
 const sources=[];
 for(const w of [...waves.filter(w=>w.age>=0),...effects.filter(e=>e.area).map(e=>({x:e.mesh.position.x,y:e.mesh.position.y,z:e.mesh.position.z,radius:e.age/e.life*e.max,color:e.color}))]){
  const angle=Math.atan2(player.z-w.z,player.x-w.x);for(const offset of[-.45,.45])sources.push({x:w.x+Math.cos(angle+offset)*w.radius,y:w.y+.8,z:w.z+Math.sin(angle+offset)*w.radius,color:w.color,strength:13,radius:12,kind:'area'});
 }
 for(const e of effects)if(e.flame)sources.push({...e.mesh.position,color:'#ff9e38',strength:11*(1-e.age/e.life),radius:10,kind:'flame'});
 lights.update(dt,projectiles,sources,player);
}
function damagePlayer(amount,goo=false,color='green'){const m=activeMember||crew.find(m=>m.id===net.self);if(!m||ending||m.player.hp<=0||m.player.hurtCooldown>0)return;damageMember(m,amount,null,goo,color);}
function spawnBrood(n,count,finalBrood=false){for(let i=0;i<count*(mode==='coop'?crew.length:1);i++){let x=n.x,z=n.z;for(let tries=0;tries<12;tries++){const ang=world.random()*Math.PI*2,rad=1+world.random()*1.1,nx=n.x+Math.cos(ang)*rad,nz=n.z+Math.sin(ang)*rad;if(world.canMove(nx,nz,.5,n.y??n.groundY??0)&&world.floor(nx,nz,n.y??n.groundY??0)!==null){x=nx;z=nz;break;}}let type=n.machine?(i%2?'spider':'drone'):n.variant===2?(i%2?'bat':'leech'):n.variant===1?(i%2?'worm':'crawler'):i%3===2?'spitter':'beetle';if((INTRODUCTIONS[type]||0)>chapterIndex)type=n.machine&&chapterIndex>=2?'drone':i%2?'crawler':'beetle';spawnActor(type,x,z,finalBrood,n.y??n.groundY??0);}}
function spriteBurst(x,y,z,row,size=3){emitVisual('burst',{x,y,z,row,size});lights?.flash({x,y,z},row===1?'#ff983f':'#77dfe9',9,.3,16);const mesh=billboard(atlas.frame('bursts',0,row),x,z,size,y-size*.5);mesh.material.depthWrite=false;mesh.material.alphaTest=.04;effects.push({mesh,life:.5,age:0,burst:row});}
function splatterFrame(color,variant=0){return color==='green'?atlas.frame('splatter',variant%4,Math.floor(variant/4)%4):atlas.frame('coloredSplatter',variant%4,['cyan','amber','violet','oil'].indexOf(color));}
function floorSplatter(x,z,color,size=2){emitVisual('decal',{x,z,color,size});const mesh=new THREE.Mesh(new THREE.PlaneGeometry(size,size),new THREE.MeshBasicMaterial({map:atlas.texture(splatterFrame(color,Math.floor(world.random()*16))),transparent:true,alphaTest:.1,depthWrite:false,opacity:.76}));mesh.rotation.set(-Math.PI/2,0,world.random()*Math.PI*2);mesh.position.set(x,(world.floor(x,z)??0)+.018+decals.length*.0001,z);scene.add(mesh);decals.push(mesh);if(decals.length>80){const old=decals.shift();scene.remove(old);old.geometry.dispose();old.material.dispose();}}
function enemyHit(a,point,lethal=false){
 emitVisual('gore',{actor:{type:a.type},point,lethal});
 const row=GORE_ROWS[a.type],size=lethal?ACTORS[a.type].size*1.8:1.0,life=lethal?.85:.29;
 const mesh=billboard(atlas.frame('originalGore',0,row),point.x,point.z,size,point.y-size*.48);mesh.material.depthWrite=false;mesh.material.alphaTest=.04;effects.push({mesh,life,age:0,gore:row,lethal});
 const count=lethal?(ACTORS[a.type].tier==='BOSS'?18:11):5,toPlayer=aimDirection(point,{x:player.x,y:player.y+1.3,z:player.z});
 for(let i=0;i<count;i++){
  const fragment=billboard(atlas.frame('originalGore',5+i%3,row),point.x,point.z,lethal?.35+world.random()*.65:.2+world.random()*.3,point.y);
  fragment.center.set(.5,.5);fragment.material.depthWrite=false;fragment.material.rotation=world.random()*6.28;
  effects.push({mesh:fragment,life:.45+world.random()*.8,age:0,vx:(world.random()-.5)*5+toPlayer.x*2,vy:1+world.random()*4,vz:(world.random()-.5)*5+toPlayer.z*2,gravity:9});
 }
 while(effects.length>320)removeEffect(effects.shift());
}
function creatureBurst(a){const g=GORE[a.type];enemyHit(a,{x:a.x,y:(a.groundY||0)+ACTORS[a.type].size*.48,z:a.z},true);floorSplatter(a.x,a.z,g.color,Math.min(5,ACTORS[a.type].size*1.8));if(Math.hypot(a.x-player.x,a.z-player.z)<5)for(let i=0;i<3;i++)visor.stain(world.random()*999,true,g.color);}

function combatEvent(e){
 if(e.type==='spawn'){spawnBrood(e.nest,e.count);particleBurst(e.nest.x,(e.nest.y||0)+.8,e.nest.z,e.nest.machine?'#8ccfd9':'#99cb36',15,2);return;}
 if(e.type==='nestBurst'){
  if(world.random()<.65)addPickup('scrap',null,e.nest.x,e.nest.z,1,25+Math.floor(world.random()*5)*10);
  spawnBrood(e.nest,e.count,true);mission.nestsDestroyed++;particleBurst(e.nest.x,(e.nest.y||0)+1.5,e.nest.z,e.nest.machine?'#f3ad51':'#a3d12d',75,10);if(e.nest.machine)spriteBurst(e.nest.x,(e.nest.y||0)+1.5,e.nest.z,1,4);ring(e.nest.x,e.nest.z,e.nest.machine?'#b4ddf4':'#adc62b',5,1);shake=.28;sfx.play('explosion',{position:e.nest,gain:1.15});
  floorSplatter(e.nest.x,e.nest.z,e.nest.machine?'oil':'green',4.5);if(Math.hypot(player.x-e.nest.x,player.z-e.nest.z)<8){for(let i=0;i<8;i++)visor.stain(world.random()*999,true,e.nest.machine?'oil':'green');toast('POD RUPTURE');}return;
 }
 if(e.type==='killed'){const a=e.actor;creatureBurst(a);sfx.play(ACTORS[a.type].family==='MACHINE'?'metal':'acid',{position:a,gain:.9,minInterval:.04});if(ACTORS[a.type].splits){spawnActor('crawler',a.x+.7,a.z,true);spawnActor('crawler',a.x-.7,a.z,true);}for(const [i,drop]of rollLoot(world.random,ACTORS[a.type].tier).entries())addPickup(drop.kind,drop.kind==='ammo'?arsenal.selected:null,a.x+(i-1)*.6,a.z,.7,drop.amount||0);return;}
 if(e.type==='damage'){const target=crew.find(m=>m.id===e.targetId)||crew.find(m=>m.id===net.self);if(target)damageMember(target,e.amount);return;}
 if(e.type==='impact'){particleBurst(e.actor.x,(e.actor.groundY||0)+1,e.actor.z,'#b7dfe0',32,7);ring(e.actor.x,e.actor.z,'#83cede',3);return;}
 if(e.type==='tell'){if(['rail','charge'].includes(e.kind)){const a=e.actor;beam({x:a.x,y:(a.groundY||0)+.1,z:a.z},{...a.target,y:(a.groundY||0)+.1},'#e1a470',a.duration,.012);}return;}
 if(e.type==='attack')attack(e.actor,e.kind,e.target);
}
function shootProjectile(a,target,angle=0,speed=9,color='#bada49',radius=.18){
 const d=ACTORS[a.type],row=d.family==='MACHINE'||a.type==='jelly'?2:a.type==='bomber'||a.type==='crawler'?3:d.blood==='violet'?1:0;
 const dir=aimDirection({x:a.x,y:(a.groundY||0)+1.1,z:a.z},target),cos=Math.cos(angle),sin=Math.sin(angle),vx=(dir.x*cos-dir.z*sin)*speed,vz=(dir.x*sin+dir.z*cos)*speed;
 const mesh=effectSprite(atlas,row,0,a.x,(a.groundY||0)+1.1,a.z,radius*4.6+.45);scene.add(mesh);
 projectiles.push({id:++projectileSerial,mesh,row,x:a.x,y:(a.groundY||0)+1.1,z:a.z,vx,vy:dir.y*speed,vz,age:0,life:5,damage:d.damage,color,radius,goo:d.family==='ALIEN',gooColor:GORE[a.type].color});
}
function shockwave(a,count=1){for(let i=0;i<count;i++)waves.push({id:++projectileSerial,x:a.x,y:a.groundY||0,z:a.z,age:-i*.42,radius:0,hit:false,damage:ACTORS[a.type].damage,color:ACTORS[a.type].color,row:ACTORS[a.type].family==='MACHINE'?2:ACTORS[a.type].blood==='violet'?3:1});particleBurst(a.x,(a.groundY||0)+.2,a.z,'#afd7e3',32,7);shake=Math.max(shake,.14);}
function attack(a,kind,target){
 const d=ACTORS[a.type];emitVisual('enemySound',{type:a.type,kind,position:{x:a.x,y:(a.groundY||0)+1,z:a.z}});sfx.enemy(d,kind,{x:a.x,y:(a.groundY||0)+1,z:a.z});
 if(['acid','fan','broodFan','orb'].includes(kind)){const n=kind==='orb'?1:kind==='broodFan'?7:5;for(let i=0;i<n;i++)shootProjectile(a,target,(i-(n-1)/2)*.15,kind==='orb'?6:8,'#b5dd48',kind==='orb'?.38:.19);if(a.phase>=2)shockwave(a);}
 else if(['bolts','crossfire'].includes(kind)){const n=kind==='crossfire'?9:3;for(let i=0;i<n;i++)shootProjectile(a,target,(i-(n-1)/2)*.1,12,i%2?'#cc8beb':'#8adaec',.14);ring(a.x,a.z,'#92e9ff',2,.3,1.2);}
 else if(kind==='rail'){
  const from={x:a.x,y:(a.groundY||0)+1.1,z:a.z},dir=aimDirection(from,target);const distance=wallDistance(from,dir,40),to={x:from.x+dir.x*distance,y:from.y+dir.y*distance,z:from.z+dir.z*distance};beam(from,to,'#a7f0ff',.32,.11);beam(from,to,'#d2a6ff',.18,.035);for(const m of livingCrew()){const p=m.player,hit=raySphere(from,dir,{x:p.x,y:p.y+1,z:p.z},.55);if(hit!==null&&hit<=distance)damageMember(m,d.damage);}particleBurst(to.x,to.y,to.z,'#91d7f8',24,4);
 }else if(['slam','cleave'].includes(kind)){shockwave(a,a.phase>1?3:2);}
 else if(['scream','summon','brood'].includes(kind)){
  for(let i=0;i<3;i++)ring(a.x,a.z,d.color,5+i*2,.75+i*.2,.5+i*.32);
  const live=nests.filter(n=>n.hp>0);for(const n of live)n.timer=Math.min(n.timer,.5);
  if(kind==='brood'&&live.length)spawnBrood(a,Math.min(3,live.length));if(kind==='summon'&&(a.summons||0)<3){a.summons=(a.summons||0)+1;spawnActor('shardling',a.x+1,a.z,true);spawnActor('shardling',a.x-1,a.z,true);}
  if(kind==='scream')for(let i=0;i<8;i++)shootProjectile(a,{x:a.x+Math.cos(i*Math.PI/4)*8,y:(a.groundY||0)+1,z:a.z+Math.sin(i*Math.PI/4)*8},0,6,'#d89bee');
 }else if(kind==='radial'){
  for(let i=0;i<12;i++)shootProjectile(a,{x:a.x+Math.cos(i*Math.PI/6)*12,y:(a.groundY||0)+1,z:a.z+Math.sin(i*Math.PI/6)*12},0,7,d.color,.2);shockwave(a,1);
 }else if(kind==='cannon'){
  for(let i=0;i<3;i++)pendingShots.push({a,target:{...target},delay:i*.14,angle:(i-1)*.045});
 }else if(kind==='heal'){
  ring(a.x,a.z,'#c497ed',8,1);for(const ally of actors)if(ally!==a&&ally.hp>0&&Math.hypot(ally.x-a.x,ally.z-a.z)<10){ally.hp=Math.min(ally.maxHp,ally.hp+25);spriteBurst(ally.x,(ally.groundY||0)+1,ally.z,2,2);}
 }else if(kind==='detonate'){
  spriteBurst(a.x,(a.groundY||0)+1,a.z,1,5);ring(a.x,a.z,'#f1a14b',4,.6);sfx.play('explosion',{position:a,gain:1});for(const m of livingCrew())if(Math.hypot(m.player.x-a.x,m.player.z-a.z,m.player.y-a.groundY)<3.5&&world.los(a.x,a.z,m.player.x,m.player.z,a.groundY+1,m.player.y+1))damageMember(m,d.damage);hurtActor(a,9999,'blast',combatEvent);
 }else if(kind==='bite'){for(const m of livingCrew())if(Math.hypot(m.player.x-a.x,m.player.z-a.z,m.player.y-(a.groundY||0))<3)damageMember(m,d.damage);ring(a.x,a.z,'#ba88e0',1,.25,1);}
 else if(['charge','leap'].includes(kind)){if(kind==='leap')shockwave(a);particleBurst(a.x,(a.groundY||0)+.3,a.z,d.color,18,3);}
}
function wallDistance(origin,dir,max=90){for(let t=.1;t<max;t+=.15)if(world.blocked(origin.x+dir.x*t,origin.y+dir.y*t,origin.z+dir.z*t))return t;return max;}
function cast(origin,dir,max=60){let distance=wallDistance(origin,dir,max),entity=null,kind=null;for(const a of actors){if(a.hp<=0)continue;const size=ACTORS[a.type].size;const t=raySphere(origin,dir,{x:a.x,y:size*.48+a.y+(a.groundY||0),z:a.z},size*.37);if(t!==null&&t<distance){distance=t;entity=a;kind='actor';}}for(const n of nests){if(n.hp<=0)continue;const t=raySphere(origin,dir,{x:n.x,y:(n.y||0)+1.3,z:n.z},1.05);if(t!==null&&t<distance){distance=t;entity=n;kind='nest';}}for(const p of infestation.patches){if(p.dead)continue;const t=raySphere(origin,dir,{x:p.x+p.nx*.22,y:p.y,z:p.z+p.nz*.22},.75);if(t!==null&&t<distance){distance=t;entity=p;kind='growth';}}for(const m of crew){if(m.player.hp<=0||!canHurtPlayer(mode,(activeMember||localCrew()).id,m.id))continue;const p=m.player,t=raySphere(origin,dir,{x:p.x,y:p.y+1,z:p.z},.58);if(t!==null&&t<distance){distance=t;entity=m;kind='player';}}return{distance,entity,kind,point:{x:origin.x+dir.x*distance,y:origin.y+dir.y*distance,z:origin.z+dir.z*distance}};}
function fire(){if(net.role==='guest'&&net.active)return;if(visor.active||!running||player.hp<=0||paused&&!activeMember)return;const w=arsenal.fire();if(!w){if(arsenal.reload&&arsenal.reload.age===0)sfx.reload(arsenal.selected,0);return;}recoil=1;const origin=new THREE.Vector3(player.x,player.y+1.65,player.z),forward=new THREE.Vector3(-Math.sin(player.yaw)*Math.cos(player.pitch),Math.sin(player.pitch),-Math.cos(player.yaw)*Math.cos(player.pitch));const crosshairHit=cast(origin,forward,w.range||60),muzzle=origin.clone().addScaledVector(forward,.52);muzzle.y-=.24;const dir=aimDirection(muzzle,crosshairHit.point),hit=cast(muzzle,dir,w.range||60);
 if(w.mode!=='flame')beam(muzzle,hit.point,w.color,.14,w.mode==='pierce'?.09:.025);shotTracer(muzzle,hit.point,w);sfx.weapon(w.id,activeMember&&activeMember.id!==net.self?{position:player}:{});emitVisual('sound',{gun:w.id,position:{x:player.x,y:player.y+1,z:player.z},shooter:(activeMember||localCrew()).id});
 if(hit.entity){hitTime=.16;if(hit.kind==='player'){damageMember(hit.entity,w.damage,(activeMember||localCrew()).id);particleBurst(hit.point.x,hit.point.y,hit.point.z,PILOTS[hit.entity.pilot].color,8,3);}else if(hit.kind==='nest')damageNest(hit.entity,w.damage,combatEvent);else if(hit.kind==='growth')damageGrowth(hit.entity,w.damage,w.mode==='flame');else{hurtActor(hit.entity,w.damage,w.mode,combatEvent);enemyHit(hit.entity,hit.point);sfx.play(ACTORS[hit.entity.type].family==='MACHINE'?'metal':'impact',{position:hit.point,gain:.45,minInterval:.06});}if(hit.kind==='nest'){particleBurst(hit.point.x,hit.point.y,hit.point.z,hit.entity.machine?'#efa565':'#98cf47',9,2);spriteBurst(hit.point.x,hit.point.y,hit.point.z,w.mode==='freeze'?3:w.mode==='chain'?2:w.mode==='blast'?1:0,w.mode==='blast'?3:1);}}
 if(w.mode==='blast'){sfx.play('explosion',{position:hit.point,gain:.75});ring(hit.point.x,hit.point.z,'#efa562',4,.5);particleBurst(hit.point.x,hit.point.y,hit.point.z,'#ef9e45',45,7);for(const a of actors)if(a!==hit.entity&&Math.hypot(a.x-hit.point.x,a.z-hit.point.z)<4&&world.los(hit.point.x,hit.point.z,a.x,a.z))hurtActor(a,w.damage*.65,w.mode,combatEvent);shake=.2;}
 if(w.mode==='chain'&&hit.entity){const target=actors.filter(a=>a!==hit.entity&&a.hp>0&&Math.hypot(a.x-hit.point.x,a.z-hit.point.z)<6&&world.los(hit.point.x,hit.point.z,a.x,a.z)).slice(0,2);for(const a of target){beam(hit.point,{x:a.x,y:(a.groundY||0)+1,z:a.z},w.color,.25,.04);hurtActor(a,w.damage*.7,'chain',combatEvent);}}
 if(w.mode==='pierce'&&hit.entity){const behind=actors.filter(a=>a!==hit.entity&&a.hp>0).map(a=>({a,t:raySphere(muzzle,dir,{x:a.x,y:(a.groundY||0)+ACTORS[a.type].size*.48,z:a.z},ACTORS[a.type].size*.37)})).filter(x=>x.t!==null&&x.t<wallDistance(muzzle,dir,60)).slice(0,3);for(const{a}of behind)hurtActor(a,w.damage*.65,'pierce',combatEvent);}
 if(w.mode==='blast')for(const p of infestation.patches)if(!p.dead&&p!==hit.entity&&Math.hypot(p.x-hit.point.x,p.y-hit.point.y,p.z-hit.point.z)<4&&world.los(hit.point.x,hit.point.z,p.x+p.nx*.3,p.z+p.nz*.3,hit.point.y,p.y))damageGrowth(p,w.damage*.7);
}

function nearestInteraction(){if(player.hp<=0)return null;let best=null,bestD=3.8;const consider=(kind,target,x,z,y,ignoreWall=false)=>{const d=Math.hypot(player.x-x,player.z-z,player.y-y);if(d<bestD&&(ignoreWall||world.los(player.x,player.z,x,z,player.y+1,y+1))){best={kind,target};bestD=d;}};
 for(const m of crew)if(m.player.down&&m.player!==player)consider('revive',m,m.player.x,m.player.z,m.player.y);
 for(const n of tasks?.nodes||[])if(mode!=='ffa'&&(tasks.interactable?.(n)??tasks.visible(n)))consider('task',n,n.x,n.z,n.y);
 for(const c of cases)if(!c.open)consider('case',c,c.x,c.z,c.y);
 if(mode!=='ffa'&&!mission.record)consider('record',recordTerminal,world.control.x,world.control.z,world.control.y);
 if(mode!=='ffa'&&!mission.choices.some(c=>c.id==='purge'))consider('purge',purgeTerminal,world.purge.x,world.purge.z,world.purge.y);
 for(const t of mode==='ffa'?[]:world.switches.filter(t=>t.timedGate||world.puzzle.required))consider('switch',t,t.x,t.z,t.y);
 if(mode!=='ffa'&&!world.accessCard.taken){const t=world.accessCard;consider('key',t,t.x,t.z,t.y);}
 for(const g of world.gates)if(!g.open)consider('gate',g,g.x,g.z,g.y,true);
 if(mode!=='ffa')consider('exit',exitDoor,world.exit.x,world.exit.z,world.exit.y);return best;
}
function interact(){if(net.active&&net.role==='guest'){net.action('interact');return true;}const i=nearestInteraction();if(!i)return false;
 if(i.kind==='revive')return true;
 if(i.kind==='task'){const result=tasks.use(i.target.id);toast(result.message||'');sfx.ui(!result.wrong);if(result.changed)saveCampaign(false);return result.accepted;}
 if(i.kind==='switch'){const result=world.useSwitch(i.target.id);toast(result.message);sfx.ui(!result.wrong);return result.accepted;}
 if(i.kind==='key'){world.accessCard.taken=true;toast('BLUE ACCESS CARD RECOVERED');sfx.play('pickup',{bus:'ui'});return true;}
 if(i.kind==='gate'){const result=world.useGate(i.target.id,player);toast(result.message);sfx.ui(result.accepted);return result.accepted;}
 if(i.kind==='case'){const c=i.target;if(c.locked&&mission.power!=='armory'){toast('ARMORY CASE SEALED · ROUTE POWER AT CONTROL');return false;}c.open=true;sfx.play('reload',{bus:'foley',gain:1,rate:.65});toast('CASE OPENING · '+WEAPON_BY_ID[c.gun].name);return true;}
 if(i.kind==='record'){mission.record=true;storyEvents.add('record');radio.send({...POWER,speaker:'ROOK',chapter:CHAPTERS[chapterIndex].title,text:storyMessage(chapterIndex,'record',{results:campaign,mission}).text+'\n'+POWER.text});toast('ACCESS RECORD RECOVERED');return true;}
 if(i.kind==='purge'){radio.send({...PURGE,speaker:'ROOK',chapter:CHAPTERS[chapterIndex].title,text:mission.record?'The copied ledger is secured. The live research bank shares power with the hatcheries. Preserve the observations, or purge the sources?':CHAPTERS[chapterIndex].discovery+' Preserve the research, or purge the sources?'});return true;}
 if(i.kind==='exit'){const boss=actors.find(a=>ACTORS[a.type].tier==='BOSS'&&a.hp>0);if(!mission.record||boss||!world.puzzle.solved||!tasks.solved){toast(!tasks.solved?tasks.objective():!mission.record?'RECOVER THE ACCESS RECORD':!world.puzzle.solved?'RESTORE THE RELAY CIRCUIT':'DEFEAT THE SECTOR GUARDIAN');return false;}finish(true);return true;}
}

function choose(index){if(net.active&&net.role==='guest'){net.action('choice'+index);return;}const decision=radio.active?.decision,value=radio.active?.choices?.[index]?.value,result=radio.choose(index,mission);if(!result.accepted)return;story(decision==='power'?'power-'+value:value);radioId=null;sfx.ui();saveTimer=30;if(mission.power==='maintenance'&&!bridgeAdded){world.bridge();buildArchitecture();bridgeAdded=true;}if(mission.purged&&!mission.purgeApplied){mission.purgeApplied=true;for(const n of nests.filter(n=>!n.machine&&n.hp>0))damageNest(n,10000,combatEvent);toast('PURGE · Nests ruptured. Final broods remain. Research lost.');}}
function finish(success){
 if(ending)return;ending=true;paused=true;shooting=false;document.exitPointerLock?.();$('ending').hidden=false;$('pause').hidden=true;
 $('ending-label').textContent=success?'RECOVERY COMPLETE':'SIGNAL LOST';$('ending-title').textContent=success?(chapterIndex===CHAPTERS.length-1?'CONTRACT CLOSED':'EXTRACTED'):'MISSION FAILED';
 const choice=mission.power==='armory'?'ARMORY POWERED':mission.power==='maintenance'?'BRIDGE RESTORED':'POWER UNCHANGED';
 const research=mission.purged?'RESEARCH LOST':mission.choices.some(c=>c.id==='purge')?'RESEARCH PRESERVED':'ARCHIVE UNRECOVERED';
 $('outcome').textContent=success?CHAPTERS[chapterIndex].exit+'\n'+`${choice} · ${research} · SCRAP SCORE ${score}`:'SCRAP RECOVERED '+score;
 $('next').textContent=success?'NEXT SECTOR':'RETRY';mission.complete=success;
 if(success&&mode==='pvpve'){const winner=activeMember||localCrew();winner.score+=1000;if(winner.id===net.self)score=winner.score;$('ending-title').textContent=PILOTS[winner.pilot].name.toUpperCase()+' EXTRACTED';$('outcome').textContent=crew.slice().sort((a,b)=>b.score-a.score).map(m=>PILOTS[m.pilot].name.toUpperCase()+' / '+m.score+' SCRAP / '+m.frags+' FRAGS').join('\n');$('next').textContent='NEXT RECOVERY';return;}
 if(mode==='ffa')return;
 if(success){campaign=campaign.filter(c=>c.chapter!==chapterIndex);campaign.push({chapter:chapterIndex,theme:THEMES[themeIndex].id,choices:[...mission.choices],purgeBeforeRecord:mission.purgeBeforeRecord===true,nestsDestroyed:mission.nestsDestroyed,score});if(chapterIndex===CHAPTERS.length-1){$('outcome').textContent+='\n'+campaignEnding(campaign);$('next').textContent='NEW RECOVERY';}saveCampaign(false,true);}
}
function start(keep=false){if(net.active&&net.role==='guest')return;if(net.role==='host')net.start({seed:Number($('seed').value)||2709,chapter:Number($('theme').value),keep});sfx.unlock();sfx.setPaused(false);pilot=$('pilot').value;setup(Number($('seed').value)||2709,Number($('theme').value),keep);$('menu').hidden=true;$('pause').hidden=true;$('ending').hidden=true;document.body.classList.remove('menu-open');running=true;paused=false;if(mode!=='ffa')story('intro');syncMissionProgress();saveCampaign(false);controller.suspend();lockMouse();sfx.ui();}
function pause(){if(!running||ending)return;controller.suspend();paused=true;shooting=false;keys.clear();sfx.setPaused(true);$('pause').hidden=false;document.exitPointerLock?.();}
function resume(){sfx.unlock();sfx.setPaused(false);paused=false;$('pause').hidden=true;controller.suspend();controllerMenu.clear();lockMouse();}

function update(dt){
 updateCrewHost(dt);matchTime+=dt;
 elapsed+=dt;sfx.setListener(player);const previousReload=arsenal.reload&&{id:arsenal.reload.id,stage:Math.floor(arsenal.reload.age/arsenal.reload.duration*3)};player.hurtCooldown=Math.max(0,player.hurtCooldown-dt);arsenal.update(dt);if(previousReload){const stage=arsenal.reload?Math.floor(arsenal.reload.age/arsenal.reload.duration*3):2;if(stage!==previousReload.stage)sfx.reload(previousReload.id,stage);}wipePose=visor.update(dt);radio.update(dt);recoil=Math.max(0,recoil-dt*8);damageFlash=Math.max(0,damageFlash-dt);hitTime=Math.max(0,hitTime-dt);toastTime=Math.max(0,toastTime-dt);shake=Math.max(0,shake-dt);
 world.tick(dt,livingCrew().map(m=>m.player));levelVisuals.update(dt);stationVisuals.update(elapsed,player,paused?null:sfx,world);infestation.tick(dt);growthVisuals.update();wheelCooldown=Math.max(0,wheelCooldown-dt);
 const movement=movePlayer(player,world,dt,localInput());
 if(movement.fell){damagePlayer(18);toast('SUIT RECOVERY · WATCH THE DROP');}
 stepTimer-=dt;if(movement.moving){bob+=dt*movement.speed*1.3;if(player.grounded&&stepTimer<=0){stepTimer=movement.speed>8?.25:.37;sfx.play('step',{bus:'foley',gain:.36});}}camera.position.set(player.x,player.y+1.65+(player.grounded?Math.sin(bob)*.025:0),player.z);camera.rotation.set(player.pitch+(shake>0?(world.random()-.5)*shake*.05:0),player.yaw,0);
 const secret=world.discover(player.x,player.z);if(secret){toast('SECRET FOUND · '+world.secrets.filter(s=>s.found).length+' / '+world.secrets.length);score+=100;sfx.play('pickup',{bus:'ui',rate:.75});if(mode!=='ffa')story('secret');}
 if(mode!=='ffa'&&nests.some(n=>n.hp>0&&Math.hypot(player.x-n.x,player.z-n.z)<20))story('discovery');
 if(mode!=='ffa'&&actors.some(a=>a.hp>0&&ACTORS[a.type].tier==='BOSS'&&Math.hypot(player.x-a.x,player.z-a.z)<24&&world.los(player.x,player.z,a.x,a.z,player.y+1.4,(a.groundY||0)+1.4)))story('guardian');
 if(localInput().fire)fire();
 for(const a of actors){const target=enemyTarget(a);if(target)updateActor(a,dt,target.player,world,e=>combatEvent({...e,targetId:target.id}));const d=ACTORS[a.type];changeFrame(a.sprite,atlas.actor(a.type,a.hitFlash>0&&a.hp>0?'hurt':a.state,a.hitFlash>0&&a.hp>0?.1-a.hitFlash:a.age,a.hitFlash>0&&a.hp>0?.12:a.duration));a.sprite.position.set(a.x,(a.groundY||0)+a.y+(d.hover&&a.hp>0?d.hover+Math.sin(elapsed*4+a.id)*.11:0),a.z);const breathe=a.hp>0&&a.state==='idle'?Math.sin(elapsed*4+a.id)*.02:0;a.sprite.scale.set(d.size*(1+breathe),d.size*(1-breathe),1);a.sprite.material.color.set(a.hitFlash>0?'#fff2c5':a.slow>0?'#7ccbe7':'#ffffff');}
 const activeCount=actors.filter(a=>a.hp>0&&Math.hypot(player.x-a.x,player.z-a.z)<32).length;
 for(const n of nests){updateNest(n,dt,activeCount<42*(mode==='coop'?crew.length:1)&&n.spawned<n.budget&&livingCrew().some(m=>Math.hypot(m.player.x-n.x,m.player.z-n.z,m.player.y-(n.y||0))<22),combatEvent);
  if(!n.machine){changeFrame(n.sprite,nestFrame(n));if(n.variant){n.sprite.material.color.set(n.state==='husk'?'#4b3a45':n.state==='hurt'?'#ffc77b':'#ffffff');n.sprite.scale.y=n.state==='husk'?.65:n.variant===2?3.45:2.9;}}
  else{changeFrame(n.sprite,atlas.frame('legacyProps',Math.floor(n.age*5)%4,0));n.sprite.material.color.set(n.state==='husk'?'#353e40':n.state==='hurt'?'#edb976':'#ffffff');if(n.state==='husk')n.sprite.scale.y=.65;}
 }
 for(const d of decorations)changeFrame(d.sprite,atlas.frame('legacyProps',Math.floor(elapsed*5)%4,d.row));
 for(const c of cases)if(c.open){c.age+=dt;changeFrame(c.sprite,atlas.frame('pickups',Math.min(7,Math.floor(c.age*9)),2));if(c.age>.75&&!c.dispensed){c.dispensed=true;addPickup('gun',c.gun,c.x,c.z,.65);}}
 for(const p of pickups){p.age+=dt;if(p.taken){if(mode!=='coop'&&mode!=='solo'&&p.age>p.respawnAt){p.taken=false;p.sprite.visible=true;}else continue;}p.sprite.position.y=p.y+.18+(p.kind==='gun'?.9:0)+Math.sin(elapsed*2+p.x)*.08;for(const m of livingCrew())if(p.age>p.delay&&Math.hypot(m.player.x-p.x,m.player.z-p.z)<1.65&&Math.abs(m.player.y-p.y)<1.8&&collectPickup(m,p))break;}
 for(let i=pendingShots.length-1;i>=0;i--){const p=pendingShots[i];p.delay-=dt;if(p.delay<=0){if(p.a.hp>0)shootProjectile(p.a,p.target,p.angle,13,'#eda255',.24);pendingShots.splice(i,1);}}
 for(let i=projectiles.length-1;i>=0;i--){const p=projectiles[i];p.age+=dt;const old={x:p.x,y:p.y,z:p.z};p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.mesh.position.set(p.x,p.y,p.z);changeFrame(p.mesh,atlas.frame('attackVfx',Math.floor(p.age*16)%8,p.row));p.mesh.material.rotation=Math.sin(p.age*7)*.16;const distance=Math.hypot(p.x-old.x,p.y-old.y,p.z-old.z),dir=aimDirection(old,p),hits=livingCrew().map(m=>({m,t:raySphere(old,dir,{x:m.player.x,y:m.player.y+1,z:m.player.z},.42+p.radius)})).filter(h=>h.t!==null&&h.t<=distance).sort((a,b)=>a.t-b.t),hit=hits[0];if(hit)damageMember(hit.m,p.damage,null,p.goo,p.gooColor);if(hit||world.blocked(p.x,p.y,p.z)||p.age>p.life){if(p.goo&&(p.row===0||p.row===1)&&waves.filter(w=>w.kind==='pool').length<12){const floor=world.floor(old.x,old.z,old.y);if(floor!==null)waves.push({id:++projectileSerial,kind:'pool',x:old.x,y:floor,z:old.z,age:0,radius:1.8,damage:p.damage*.35,color:p.color,row:p.row===1?3:1,life:3,hits:[]});}particleBurst(p.x,p.y,p.z,p.color,10,3);spriteBurst(p.x,p.y,p.z,p.row===2?2:p.row===3?1:0,.8);scene.remove(p.mesh);p.mesh.material.dispose();sfx.play('impact',{position:p,gain:.3,minInterval:.07});projectiles.splice(i,1);}else if(Math.floor(p.age*10)!==Math.floor((p.age-dt)*10))beam(old,p,p.color,.14,.025);}
 for(let i=waves.length-1;i>=0;i--){
  const w=waves[i];w.age+=dt;if(w.age<0)continue;const previous=w.radius;w.radius=w.kind==='pool'?1.8:w.age*8;updateWaveVisual(w);w.hits??=[];w.nextHit??={};
  for(const m of livingCrew()){const p=m.player,d=Math.hypot(p.x-w.x,p.z-w.z),touching=w.kind==='pool'?d<=w.radius&&w.age>=(w.nextHit[m.id]||0):!w.hits.includes(m.id)&&d>=previous-.5&&d<=w.radius+.5;
   if(touching&&Math.abs(p.y-w.y)<.7&&world.los(w.x,w.z,p.x,p.z,w.y+.4,p.y+.4)){damageMember(m,w.damage);w.hits.push(m.id);w.nextHit[m.id]=w.age+.8;}
  }
  if(w.kind==='pool'?w.age>w.life:w.radius>10){removeEffect(w);waves.splice(i,1);}
 }

 advanceEffects(dt);syncMissionProgress();tasks.tick(dt,livingCrew().map(m=>({...m.player,revive:inputFor(m.id).revive})));taskVisuals.update(camera);updateLights(dt);updateCrewSprites(dt);updateNavigation(dt);saveTimer+=dt;if(saveTimer>30){saveTimer=0;saveCampaign(false);}checkMatch(dt);
 exitDoor.material.color.set(mission.record&&!actors.some(a=>ACTORS[a.type].tier==='BOSS'&&a.hp>0)?'#9bd7b2':'#d2b19c');
 drawHud();
}
function populateArmory(){const container=$('armory-preview');container.replaceChildren();for(const w of WEAPONS){const item=document.createElement('div');item.className='armory-item';const c=document.createElement('canvas');c.width=156;c.height=100;const x=c.getContext('2d');x.imageSmoothingEnabled=false;x.drawImage(atlas.frame('pickups',WEAPON_BY_ID[w.id].index,0),0,0,156,100);item.append(c,document.createTextNode(w.name));const small=document.createElement('small');small.textContent=w.ammoName.toUpperCase();item.append(small);container.append(item);}}
function drawHud(){const w=WEAPON_BY_ID[arsenal.selected],slot=arsenal.slots[w.id];$('health').textContent=Math.ceil(player.hp);$('total-ammo').textContent=Object.values(arsenal.slots).reduce((sum,s)=>sum+(s.owned?s.mag+s.reserve:0),0);$('score').textContent=String(score).padStart(6,'0');$('region').textContent=world.region(player.x,player.z);$('secret-count').textContent=world.secrets.filter(s=>s.found).length+' / '+world.secrets.length+' SECRETS';$('health-bar').style.width=player.hp+'%';$('mag').textContent=slot.mag.toString().padStart(2,'0');$('reserve').textContent=' / '+slot.reserve;$('gun-name').textContent=w.name;$('reload-status').textContent=arsenal.reload?`RELOADING ${Math.floor(arsenal.reload.age/arsenal.reload.duration*100)}%`:visor.active?'WIPING':'';
 const heading=((player.yaw*-180/Math.PI)%360+360)%360;$('heading').textContent=['N','NE','E','SE','S','SW','W','NW'][Math.round(heading/45)%8]+' · '+Math.round(heading).toString().padStart(3,'0');
 const bossAlive=actors.some(a=>ACTORS[a.type].tier==='BOSS'&&a.hp>0);$('objective').textContent=mode==='ffa'?'20 FRAGS / '+Math.max(0,Math.ceil(600-matchTime))+'s':!tasks.solved?'◇ '+tasks.objective():!world.accessCard.taken?'◇ FIND BLUE ACCESS':!world.puzzle.solved?'◇ RESTORE RELAY CIRCUIT':!mission.record?'◇ RECOVER ARCHIVE':bossAlive?'◇ DEFEAT GUARDIAN':'◇ REACH EXTRACTION';$('toast').style.opacity=toastTime>0?1:0;$('hitmarker').style.opacity=hitTime>0?1:0;
 const forward=new THREE.Vector3();camera.getWorldDirection(forward);const target=cast(camera.position,forward,32);$('target').textContent=target.entity?(target.kind==='nest'?(target.entity.machine?'FABRICATION VENT':'BROOD POD'):target.kind==='growth'?'WALL INFESTATION':target.kind==='player'?PILOTS[target.entity.pilot].name.toUpperCase():ACTORS[target.entity.type].name.toUpperCase())+'  '+Math.ceil(target.kind==='player'?target.entity.player.hp:target.entity.hp):'';
 const near=nearestInteraction();$('interaction').textContent=player.down?'DOWNED / HOLD ON FOR REVIVAL':player.dead?'REDEPLOYING '+Math.ceil(Math.max(0,4-(player.downAge||0)))+'s':near?near.kind==='revive'?'HOLD E / REVIVE '+PILOTS[near.target.pilot].name.toUpperCase()+' '+Math.round((near.target.player.revive||0)/3*100)+'%':near.kind==='task'?'E / '+near.target.label:near.kind==='case'?`E · ${near.target.locked&&mission.power!=='armory'?'SEALED ARMORY CASE':'OPEN WEAPON CASE'}`:near.kind==='switch'?`E · ${near.target.timedGate?'OPEN TIMED SHUTTER':'RELAY '+(near.target.index+1)}`:near.kind==='key'?'E · RECOVER BLUE ACCESS':near.kind==='gate'?'E · '+near.target.label:near.kind==='record'?'E · RECOVER ARCHIVE / ROUTE POWER':near.kind==='purge'?'E · ARCHIVE CONTROL':'E · EXTRACTION':'';
 $('key-status').textContent=world.accessCard.taken?'BLUE ACCESS ✓':'BLUE ACCESS —';
 if(inputDevice==='controller')$('interaction').textContent=$('interaction').textContent.replace(/^E([ /·])/,'Y / △$1').replace('HOLD E /','HOLD Y / △ /');
 const msg=radio.active;$('radio').classList.toggle('closed',!msg||radio.dismissed);$('radio-status').textContent=msg?(msg.choices?'DECISION REQUIRED':'INCOMING · '+msg.speaker):'MISSION LINK';
 if(msg){$('speaker').textContent='SCRAPPER';$('role').textContent=msg.chapter||'SALVAGE / RECOVERY';$('dialogue').textContent=radio.visibleText();const pc=$('portrait').getContext('2d');helmetPortrait(pc,atlas.images.hudSkin,104,104,elapsed,radio.visibleText().length<msg.text.length);if(radioId!==msg.id){radioId=msg.id;$('choices').replaceChildren();for(const[c,option]of(msg.choices||[]).entries()){const b=document.createElement('button');b.textContent=`${inputDevice==='controller'?(c===0?'◀':'▶'):(c===0?'Z':'X')} · ${option.label}`;const sub=document.createElement('small');sub.textContent=option.effect;b.append(sub);b.onclick=()=>choose(c);$('choices').append(b);}}}
 else{radioId=null;$('choices').replaceChildren();}
}
function drawOverlay(){const width=overlay.width,height=overlay.height;ctx.clearRect(0,0,width,height);ctx.imageSmoothingEnabled=false;if(!ready)return;
 for(const s of visor.stains){const size=s.size*height*2,colors=s.colors||[s.color||'green'];ctx.save();ctx.translate(s.x*width,s.y*height);for(let n=0;n<colors.length;n++){ctx.globalAlpha=(s.opacity||.88)/(colors.length>1?1.7:1);const art=splatterFrame(colors[n],Math.floor(s.x*13+s.y*17)%16);ctx.drawImage(art,-size/2+n*size*.07,-size/2+n*size*.015,size,size);}ctx.restore();}
 const hudHeight=Math.min(height*.28,width*207/1672),baseline=height-hudHeight+height*.025,gunHeight=Math.max(height*.22,(baseline-height*.53)/.91),gunWidth=gunHeight/.889,move=Math.sin(bob)*2;
 let frame;let gx=width/2-gunWidth/2,gy=baseline-gunHeight+recoil*9;
 if(visor.active&&wipePose){
  frame=atlas.frame('reload-'+arsenal.selected,0,0,pilot);gy+=height*.8*wipePose.gunDrop;
 }else if(arsenal.reload){const step=Math.min(11,Math.floor(arsenal.reload.age/arsenal.reload.duration*12)),f=step===11?0:step;frame=atlas.frame('reload-'+arsenal.selected,f%4,Math.floor(f/4),pilot);}else frame=atlas.frame('reload-'+arsenal.selected,0,0,pilot);
 if(!visor.active||!wipePose||wipePose.gunDrop<1)ctx.drawImage(frame,gx,gy+move,gunWidth,gunHeight);
 if(recoil>.65&&!arsenal.reload&&!visor.active){const row=arsenal.selected==='arc'?2:arsenal.selected==='frost'?3:arsenal.selected==='flame'||arsenal.selected==='rockets'?1:0,size=38+recoil*30;ctx.drawImage(atlas.frame('bursts',Math.min(3,Math.floor((1-recoil)*10)),row),width/2-size/2,gy+gunHeight*.09-size/2,size,size);}
 if(visor.active&&wipePose?.visible){const img=atlas.wipeFrame('wipe',wipePose.frame,0,pilot,visor.palette),h=height*.93,w=h*img.width/img.height;ctx.drawImage(img,width*wipePose.x-w*.44,height*wipePose.y-h*.35,w,h);}
 drawDashboard(ctx,atlas,width,height,arsenal,player,{chapter:chapterIndex,score,key:world.accessCard.taken,secrets:world.secrets.filter(s=>s.found).length,capacity:WEAPON_BY_ID[arsenal.selected].mag,weaponName:WEAPON_BY_ID[arsenal.selected].name});if(mapOpen)drawMap(width,height);
 if(damageFlash>0){ctx.fillStyle=`rgba(163,53,37,${damageFlash*.25})`;ctx.fillRect(0,0,width,height);}
}

function populateChapters(){const select=$('theme');select.replaceChildren();for(const[c,chapter]of CHAPTERS.entries()){const option=document.createElement('option');option.value=c;option.textContent=String(c+1).padStart(2,'0')+' / '+chapter.title.toUpperCase();select.append(option);}select.value=chapterIndex;const journal=$('contract-journal');journal.replaceChildren();for(const[i,c]of CHAPTERS.entries()){const entry=document.createElement('details'),title=document.createElement('summary');title.textContent=c.act+' · '+c.title;entry.append(title);for(const paragraph of recoveryJournal(i,{mission:i===chapterIndex?mission:null,results:campaign})){const body=document.createElement('p');body.textContent=paragraph;entry.append(body);}journal.append(entry);}}

function drawMap(width,height){const mx=width*.17,my=height*.13,mw=width*.66,mh=height*.62,b=world.bounds,scale=Math.min(mw/(b.x2-b.x1),mh/(b.z2-b.z1));ctx.fillStyle='#071017ed';ctx.fillRect(mx-22,my-30,mw+44,mh+65);ctx.strokeStyle='#e5a647';ctx.lineWidth=3;ctx.strokeRect(mx-22,my-30,mw+44,mh+65);for(const c of world.cells.values()){if(c.room.startsWith('secret')&&!world.secrets.some(s=>s.found&&s.room===c.room))continue;ctx.fillStyle=c.gap?'#090b0e':c.y<0?'#3a697e':c.y>5?'#b58a50':'#536c73';ctx.fillRect(mx+(c.x*2-b.x1)*scale,my+(c.z*2-b.z1)*scale,2*scale+.1,2*scale+.1);}const marker=(p,color,size=4)=>{ctx.fillStyle=color;ctx.fillRect(mx+(p.x-b.x1)*scale-size/2,my+(p.z-b.z1)*scale-size/2,size,size);};marker(world.control,'#f1dc9b');marker(world.exit,'#9af1d1');for(const l of world.lifts)marker(l,'#edaf51',5);marker(player,'#ffffff',7);ctx.fillStyle='#ffe1a0';ctx.font='10px Pixel';ctx.fillText('STATION PLAN / M CLOSE',mx,my-10);ctx.font='7px Pixel';ctx.fillText('AMBER UPPER DECK · BLUE LOWER DECK · ORANGE LIFT',mx,my+mh+20);}

function resize(){renderer.setSize(innerWidth,innerHeight);camera.aspect=innerWidth/innerHeight;camera.updateProjectionMatrix();overlay.width=innerWidth;overlay.height=innerHeight;}
addEventListener('resize',resize);resize();
document.addEventListener('mousemove',e=>{if(!running||paused||document.pointerLockElement!==view)return;setInputDevice('mouse');player.yaw-=e.movementX*.002;player.pitch=Math.max(-1.25,Math.min(1.25,player.pitch-e.movementY*.002));});
document.addEventListener('keydown',e=>{setInputDevice('mouse');if(e.code==='Escape'||e.code==='KeyP'){if(e.repeat)return;if(running&&!ending){e.preventDefault();paused?resume():pause();}return;}if(['Space','Tab','ArrowUp','ArrowDown'].includes(e.code)&&running)e.preventDefault();if(!running||paused)return;keys.add(e.code);if(e.repeat)return;if(e.code==='KeyE')interact();if(e.code==='KeyR')reloadWeapon();if(e.code==='KeyQ')wipeVisor();if(e.code==='Tab')radio.toggle();if(e.code==='KeyM')mapOpen=!mapOpen;if(e.code==='KeyZ')choose(0);if(e.code==='KeyX')choose(1);if(e.code==='KeyP')pause();if(/^Digit[1-7]$/.test(e.code)&&!visor.active){const w=WEAPONS[Number(e.code.slice(-1))-1];if(!arsenal.equip(w.id))toast('Find '+w.name+' in a supply case');}});
document.addEventListener('keyup',e=>keys.delete(e.code));
view.addEventListener('wheel',e=>{if(!running||paused)return;e.preventDefault();if(visor.active||wheelCooldown>0)return;arsenal.equip(nextOwnedWeapon(arsenal,e.deltaY));wheelCooldown=.13;sfx.ui();},{passive:false});
view.addEventListener('mousedown',e=>{setInputDevice('mouse');if(e.button!==0||!running||paused)return;if(document.pointerLockElement!==view)lockMouse();shooting=true;});document.addEventListener('mouseup',()=>shooting=false);
document.addEventListener('pointerlockchange',()=>{if(!document.pointerLockElement&&running&&!ending)pause();});addEventListener('blur',()=>{controller.suspend();keys.clear();shooting=false;if(running)pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden){controller.suspend();if(running)pause();}});
$('start').onclick=()=>{net.leave();campaign=[];entryLoadout=null;entryScore=score=0;start();};$('pause-button').onclick=pause;$('resume').onclick=resume;$('restart').onclick=()=>start();$('radio-toggle').onclick=()=>radio.toggle();$('new-seed').onclick=()=>{$('seed').value=1+Math.floor(Math.random()*999999);setup(Number($('seed').value),Number($('theme').value));};$('theme').onchange=()=>{if(ready)setup(Number($('seed').value),Number($('theme').value));};$('pilot').onchange=()=>pilot=$('pilot').value;
$('next').onclick=()=>{const success=mission.complete;if(success){$('theme').value=(chapterIndex+1)%CHAPTERS.length;$('seed').value=Number($('seed').value)+107;if(chapterIndex===CHAPTERS.length-1){campaign=[];entryLoadout=null;entryScore=score=0;}}start(success&&chapterIndex!==CHAPTERS.length-1);};$('return-menu').onclick=returnTitle;
function setInputDevice(device){if(inputDevice===device)return;inputDevice=device;radioId=null;if(device==='mouse')controllerMenu.clear();}
function lockMouse(){if(inputDevice==='controller')return;try{view.requestPointerLock?.()?.catch(()=>{});}catch{}}
function pollController(dt){
 const context=ending?'ending':paused?'pause':running?'mission':'title';if(controllerContext!==context){controller.suspend();controllerContext=context;}
 let pads=[];try{pads=navigator.getGamepads?.()||[];}catch{}
 const state=controller.poll(pads,dt,!document.hidden&&document.hasFocus());
 if(state.lost&&inputDevice==='controller'&&running&&!ending){pause();return;}
 if(state.active)setInputDevice('controller');
 if(!state.connected)return;
 if(state.pressed[PAD.pause]&&running&&!ending){paused?resume():pause();return;}
 if(!running||paused||ending){controllerMenu.update(ending?$('ending'):paused?$('pause'):$('menu'),state,dt,()=>{if(paused)resume();else if(ending)returnTitle();});return;}
 controllerMenu.clear();
 if(player.hp<=0)return;
 const turn=lookDelta(state.look,dt,controller.settings,state.held[PAD.aim]);player.yaw+=turn.yaw;player.pitch=Math.max(-1.25,Math.min(1.25,player.pitch+turn.pitch));
 const p=state.pressed;
 if(p[PAD.reload])reloadWeapon();if(p[PAD.use])interact();if(p[PAD.wipe]){if(mapOpen)mapOpen=false;else wipeVisor();}
 if(p[PAD.map])mapOpen=!mapOpen;if(p[PAD.comms])radio.toggle();
 if(p[PAD.left])choose(0);if(p[PAD.right])choose(1);
 if(!visor.active&&(p[PAD.previous]||p[PAD.next])){arsenal.equip(nextOwnedWeapon(arsenal,p[PAD.next]?1:-1));sfx.ui();}
}
function updateControllerSettings(){controller.settings=controllerSettings({sensitivity:Number($('pad-sensitivity').value),deadzone:Number($('pad-deadzone').value),invertY:$('pad-invert').value==='yes'});$('pad-sensitivity-value').textContent=controller.settings.sensitivity.toFixed(2);$('pad-deadzone-value').textContent=Math.round(controller.settings.deadzone*100)+'%';try{localStorage.setItem('scrapper-controller',JSON.stringify(controller.settings));}catch{}}
$('pad-sensitivity').value=controller.settings.sensitivity;$('pad-deadzone').value=controller.settings.deadzone;$('pad-invert').value=controller.settings.invertY?'yes':'no';
for(const id of['pad-sensitivity','pad-deadzone','pad-invert'])$(id).addEventListener('input',updateControllerSettings);
$('pad-invert').addEventListener('change',updateControllerSettings);updateControllerSettings();
let last=performance.now();function frame(now){requestAnimationFrame(frame);const dt=Math.min(.035,(now-last)/1000);last=now;if(!ready)return;pollController(dt);if(running&&(!paused||net.active)&&!ending){if(net.active&&net.role==='guest')updateGuest(dt);else update(dt);}if(net.role==='host'&&net.active)net.publish(()=>{const state=networkSnapshot();net.lastPacketBytes=JSON.stringify(state).length;return state;},now);if(net.role==='guest'&&net.active&&running)net.input(localInput(),now);else if(!running){camera.position.set(world.start.x,world.start.y+1.7,world.start.z);camera.rotation.set(-.02,Math.sin(now*.00006)*.15,0);}renderer.render(scene,camera);drawOverlay();}
document.body.classList.add('menu-open');requestAnimationFrame(frame);
atlas.load((done,total)=>{$('load-status').textContent=`Loading art ${done} / ${total}`;}).then(()=>{ready=true;installChrome(atlas);populateChapters();setup();$('start').disabled=false;$('start').textContent='▶ DEPLOY SOLO';$('load-status').textContent='';populateArmory();refreshSaves();window.scrapperReady=true;}).catch(err=>{$('load-status').textContent=err.message;console.error(err);});

// Deterministic local verification hooks; all mutations call the same live gameplay functions.
window.scrapper={snapshot:()=>({controller:{connected:controller.state.connected,armed:controller.armed,device:inputDevice,settings:controller.settings,input:localInput()},mapOpen,net:{packetBytes:net.lastPacketBytes||0,role:net.role,code:net.code,active:net.active,mode,members:crew.map(m=>({id:m.id,pilot:m.pilot,player:{...m.player},score:m.score,frags:m.frags,weapon:m.arsenal.selected})),metrics:net.metrics},tasks:tasks?.snapshot(),compass:compass?.contacts,route:{next:guide?.next,portal:guide?.portal,relative:guide?.relative,action:guide?.action,status:guide?.status,revision:guide?.revision,distance:guide?.distance,length:guide?.route.length},lights:lights?.snapshot(),infestation:infestation?.snapshot(),station:stationVisuals?.snapshot(elapsed),ready,running,paused,theme:THEMES[themeIndex].id,seed:world?.seed,player:{...player},mission:{...mission},radio:{active:radio?.active,text:radio?.visibleText(),history:radio?.history.map(m=>m.id),queue:radio?.queue.map(m=>({id:m.id,text:m.text}))},chapter:chapterIndex,score,layout:{name:world.name,cells:world.cells.size,bounds:world.bounds},puzzle:{...world.puzzle},lifts:world.lifts.map(l=>({...l})),gates:world.gates.map(g=>({...g})),secrets:world.secrets.map(s=>({...s})),weapon:arsenal?.selected,ammo:arsenal?.slots,reload:arsenal?.reload,nests:nests.map(({id,hp,state,burstDone})=>({id,hp,state,burstDone})),actors:actors.map(({id,type,hp,state,x,z,groundY})=>({id,type,hp,state,x,z,y:groundY})),cases:cases.map(({gun,open,dispensed})=>({gun,open,dispensed})),pickups:pickups.map(({kind,gun,taken})=>({kind,gun,taken})),wipe:{asset:SPECS.wipe.path,pose:wipePose,variant:visor?.lastVariant,stains:visor?.stains.length,palette:visor?.palette,active:!!visor?.active,colors:visor?.stains.map(s=>s.colors)},sound:sfx.snapshot(),effects:{sprites:effects.filter(e=>e.mesh.isSprite).length,ribbons:effects.filter(e=>e.mesh.userData.beam).length,projectiles:projectiles.length,pixelProjectiles:projectiles.every(p=>p.mesh.isSprite),positions:projectiles.slice(0,12).map(p=>({x:p.x,y:p.y,z:p.z,row:p.row,size:p.mesh.scale.x})),tracers:effects.filter(e=>e.tracer).length,flames:effects.filter(e=>e.flame).length,areaSprites:waves.reduce((n,w)=>n+(w.mesh?.children.length||0),0)+effects.filter(e=>e.area).reduce((n,e)=>n+e.mesh.children.length,0),waves:waves.length},renderer:{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles},campaign}),
 save:()=>saveCampaign(true),load:()=>loadCampaign(),room:{host:(mode='coop',pilotId=pilot)=>net.create(pilotId,mode),join:(code,pilotId=pilot)=>net.join(code,pilotId),start:()=>start(),leave:()=>returnTitle()},taskNodes:()=>tasks.nodes,taskReadouts:()=>tasks.nodes.map(n=>({id:n.id,text:taskVisuals.readout(n),visible:tasks.visible(n),active:tasks.interactable?.(n)??tasks.visible(n)})),damagePlayer:(amount,id=net.self)=>damageMember(crew.find(m=>m.id===id),amount),step:seconds=>{for(let t=0;t<seconds;t+=1/60)update(1/60);},start:()=>start(),interact,choose,fire,reload:reloadWeapon,equip:id=>arsenal.equip(id),pause,resume,
 teleport:(x,z,y=world.floor(x,z)??0)=>{Object.assign(player,{x,z,y,vy:0,grounded:true});camera.position.set(x,y+1.65,z);},look:(yaw,pitch=0)=>{player.yaw=yaw;player.pitch=pitch;camera.rotation.set(pitch,yaw,0);},
 locations:()=>({stationProps:world.stationProps,start:world.start,control:world.control,purge:world.purge,exit:world.exit,cases:world.cases,gap:world.gap,nests:world.nests,rooms:world.rooms,lifts:world.lifts,switches:world.switches,key:world.accessCard,gates:world.gates,stairs:world.stairs}),input:(code,down)=>down?keys.add(code):keys.delete(code),map:()=>mapOpen=!mapOpen,loot:(tier='ENEMY')=>{for(const d of rollLoot(world.random,tier))addPickup(d.kind,d.kind==='ammo'?arsenal.selected:null,player.x,player.z,0,d.amount||0);},
 damageGrowth:(id,amount=20,flame=false)=>{const p=infestation.patches.find(p=>p.id===id);if(p)damageGrowth(p,amount,flame);return p;},stain:(colors=['green'])=>{for(let i=0;i<8;i++)visor.stain(i*.79,true,colors[i%colors.length]);},wipe:wipeVisor,damageNest:index=>damageNest(nests[index],1000,combatEvent),attack:(id,kind)=>{const a=actors.find(a=>a.type===id);if(a)attack(a,kind,{x:player.x,y:player.y+1,z:player.z});},
 sound:id=>{sfx.unlock();return sfx.weapon(id);},hurt:(id,damage=25)=>{const a=actors.find(a=>a.id===id);if(!a)return false;const dead=hurtActor(a,damage,'bullet',combatEvent);if(!dead)enemyHit(a,{x:a.x,y:(a.groundY||0)+1,z:a.z});return dead;},loadSector:index=>{setup(Number($('seed').value),index);},journal:()=>CHAPTERS.map((c,i)=>({title:c.title,paragraphs:recoveryJournal(i,{mission:i===chapterIndex?mission:null,results:campaign})})),art:()=>({images:Object.keys(atlas.images).length,frames:atlas.cache.size})};

function advanceEffects(dt){ for(let i=effects.length-1;i>=0;i--){const e=effects[i];e.age+=dt;if(e.age>=e.life){removeEffect(e);effects.splice(i,1);continue;}if(e.tracer){const t=Math.min(1,e.age/e.life);e.mesh.position.set(e.from.x+(e.to.x-e.from.x)*t,e.from.y+(e.to.y-e.from.y)*t,e.from.z+(e.to.z-e.from.z)*t);}
 if(e.area){animateArea(e.mesh,atlas,e.age/e.life*e.max,e.age,Math.min(1,(e.life-e.age)*4));continue;}if(e.flame){changeFrame(e.mesh,atlas.frame('areaVfx',Math.min(7,Math.floor(e.age/e.life*8)),0));const size=.65+e.age/e.life*1.8;e.mesh.scale.set(size,size,1);e.mesh.material.opacity=Math.min(1,(e.life-e.age)*7);continue;}if(e.vfx!==undefined){changeFrame(e.mesh,atlas.frame('attackVfx',e.ring?Math.min(7,Math.floor(e.age/e.life*8)):(Math.floor(e.age*18)+(e.offset||0))%8,e.vfx));if(e.mesh.userData.beam)orientBeam(e.mesh,camera);}if(e.gore!==undefined){changeFrame(e.mesh,atlas.frame('originalGore',Math.min(7,Math.floor(e.age/e.life*8)),e.gore));}else if(e.deathBurst!==undefined){changeFrame(e.mesh,atlas.frame('deathBursts',Math.min(7,1+Math.floor(e.age/e.life*7)),e.deathBurst));}else if(e.burst!==undefined){changeFrame(e.mesh,atlas.frame('bursts',Math.min(3,Math.floor(e.age/e.life*4)),e.burst));}else if(e.ring){e.mesh.scale.setScalar(.1+e.age/e.life*e.max*2.6);e.mesh.material.opacity=1-e.age/e.life;}else if(e.vx!==undefined){e.vy-=e.gravity*dt;e.mesh.position.x+=e.vx*dt;e.mesh.position.y+=e.vy*dt;e.mesh.position.z+=e.vz*dt;e.mesh.material.rotation+=dt*4;e.mesh.material.opacity=1-e.age/e.life;const floor=(world.floor(e.mesh.position.x,e.mesh.position.z,e.mesh.position.y)??-22)+.04;if(e.mesh.position.y<floor){e.mesh.position.y=floor;e.vy=0;e.vx*=.9;e.vz*=.9;}}else e.mesh.material.opacity=1-e.age/e.life;}
}

function localCrew(){return crew.find(m=>m.id===net.self)||crew[0];}
function livingCrew(){return crew.filter(m=>m.player.hp>0);}
function localInput(){const enabled=!paused&&!ending&&player?.hp>0,pad=controller.state,h=pad.held;return{forward:enabled?Math.max(-1,Math.min(1,Number(keys.has('KeyW'))-Number(keys.has('KeyS'))-pad.move.y)):0,strafe:enabled?Math.max(-1,Math.min(1,Number(keys.has('KeyD'))-Number(keys.has('KeyA'))+pad.move.x)):0,sprint:enabled&&(keys.has('ShiftLeft')||!!h[PAD.sprint]),jump:enabled&&(keys.has('Space')||pad.jump),revive:enabled&&(keys.has('KeyE')||!!h[PAD.use]),fire:enabled&&(shooting||!!h[PAD.fire]),yaw:player?.yaw||0,pitch:player?.pitch||0,weapon:arsenal?.selected||'bolt',paused:!enabled};}
function inputFor(id){return id===net.self?localInput():net.inputFor(id,performance.now());}
function initializeCrew(keep=false){const old=new Map(crew.map(m=>[m.id,m]));crew=[];for(const [i,record]of(net.active?net.members:[{id:net.self,pilot}]).entries()){const own=record.id===net.self,p={...world.start,x:world.start.x+(i%2)*2,z:world.start.z+Math.floor(i/2)*2,vy:0,yaw:0,pitch:0,hp:100,grounded:true,safe:{...world.start},hurtCooldown:2};const m={...record,player:own?player:p,arsenal:own?arsenal:new Arsenal(),visor:own?visor:new VisorState(),score:own?score:0,frags:0,deaths:0,walkAge:0,actions:{}};if(own){pilot=record.pilot;$('pilot').value=pilot;}if(mode==='ffa'||mode==='pvpve'){const spawn=respawnPoint(world,crew,world.random);Object.assign(m.player,spawn,{safe:{...spawn}});}if(old.get(record.id)&&mode==='coop'&&keep){m.arsenal.slots=structuredClone(old.get(record.id).arsenal.slots);}crew.push(m);if(!own){m.sprite=billboard(atlas.frame('crew-'+m.pilot+'-bolt',0,0),m.player.x,m.player.z,2.6,m.player.y);}}
 $('save-game').hidden=net.active;$('restart').hidden=net.active;$('room-deploy').hidden=net.role!=='host';}
function withMember(m,fn){if(m===localCrew())return fn();const saved={player,arsenal,visor,score,activeMember};player=m.player;arsenal=m.arsenal;visor=m.visor;score=m.score;activeMember=m;try{return fn();}finally{m.score=score;({player,arsenal,visor,score,activeMember}=saved);}}
function damageMember(m,amount,attacker=null,goo=false,color='green'){if(!m||m.player.hp<=0||m.player.hurtCooldown>0||ending)return false;const died=hitPlayer(m,amount,{mode,attacker});if(goo)for(let i=0;i<3;i++)m.visor.stain(world.random()*999,true,color);if(m.id===net.self){damageFlash=.33;shake=.13;sfx.play('impact',{bus:'foley',gain:1.2});}if(died){if(attacker&&attacker!==m.id){const killer=crew.find(p=>p.id===attacker);if(killer){killer.frags++;killer.score+=100;if(killer.id===net.self)score=killer.score;}}emitVisual('burst',{x:m.player.x,y:m.player.y+1,z:m.player.z,row:2,size:2});if(mode==='solo')finish(false);}return died;}
function enemyTarget(a){return livingCrew().sort((m,n)=>Math.hypot(m.player.x-a.x,m.player.z-a.z,m.player.y-(a.groundY||0))-Math.hypot(n.player.x-a.x,n.player.z-a.z,n.player.y-(a.groundY||0)))[0];}
function collectPickup(m,p){const a=m.arsenal,player=m.player;if(p.kind==='health'){if(player.hp>=100)return false;player.hp=Math.min(100,player.hp+(p.amount||25));}else if(p.kind==='scrap'){m.score+=p.amount||25;if(m.id===net.self)score=m.score;}else if(p.kind==='gun'){a.unlock(p.gun);if(mode==='coop')for(const other of crew)if(other!==m){const old=other.arsenal.selected;other.arsenal.unlock(p.gun);other.arsenal.equip(old);}}else a.addAmmo(p.gun,WEAPON_BY_ID[p.gun].mag*2);p.taken=true;p.respawnAt=p.age+30;p.sprite.visible=false;if(m.id===net.self){toast(p.kind==='gun'?'ACQUIRED / '+WEAPON_BY_ID[p.gun].name:p.kind==='scrap'?'+'+(p.amount||25)+' SCRAP':p.kind==='health'?'SUIT RESTORED':'AMMO RECOVERED');sfx.play('pickup',{bus:'ui'});}saveCampaign(false);return true;}
function reloadWeapon(){if(net.active&&net.role==='guest'){net.action('reload');return;}if(player.hp>0&&!visor.active&&arsenal.startReload())sfx.reload(arsenal.selected,0);}
function wipeVisor(){if(net.active&&net.role==='guest'){net.action('wipe');return true;}if(player.hp>0&&!arsenal.reload&&visor.wipe()){if(!activeMember)sfx.play('wipe',{bus:'foley'});return true;}return false;}
function updateCrewHost(dt){if(!crew.length)return;localCrew().score=score;for(const m of crew){if(m.id===net.self)continue;const input=inputFor(m.id);m.player.hurtCooldown=Math.max(0,m.player.hurtCooldown-dt);m.arsenal.update(dt);m.visor.update(dt);if(m.player.hp>0){if(Number.isFinite(input.yaw))m.player.yaw=input.yaw;if(Number.isFinite(input.pitch))m.player.pitch=input.pitch;const motion=movePlayer(m.player,world,dt,input);if(motion.fell)damageMember(m,18);m.moving=motion.moving;if(m.moving)m.walkAge+=dt;m.arsenal.equip(input.weapon);withMember(m,()=>{for(const [key,value]of Object.entries(input.actions||{})){if(value>(m.actions[key]||0)){m.actions[key]=value;if(key==='interact')interact();if(key==='reload')reloadWeapon();if(key==='wipe')wipeVisor();if(key.startsWith('choice'))choose(Number(key.at(-1)));}}if(input.fire&&!input.paused)fire();});}}
 for(const event of updateRevives(crew,dt,world,inputFor)){emitVisual('burst',{x:crew.find(m=>m.id===event.target).player.x,y:crew.find(m=>m.id===event.target).player.y+1,z:crew.find(m=>m.id===event.target).player.z,row:3,size:2});toast('SALVAGER REVIVED');}
 for(const m of crew)if(m.player.dead&&mode!=='solo'){m.player.downAge=(m.player.downAge||0)+dt;if(m.player.downAge>4){const spawn=respawnPoint(world,crew,world.random);Object.assign(m.player,spawn,{hp:100,dead:false,down:false,vy:0,grounded:true,hurtCooldown:2,safe:{...spawn}});m.arsenal.reload=null;for(const w of WEAPONS)if(m.arsenal.slots[w.id].owned){m.arsenal.slots[w.id].mag=w.mag;m.arsenal.slots[w.id].reserve=Math.max(m.arsenal.slots[w.id].reserve,w.mag*2);}m.visor.stains=[];}}
}
function updateCrewSprites(dt){for(const m of crew){if(m.id===net.self||!m.sprite)continue;const p=m.player,frame=directionalFrame(p.yaw,player,p,m.walkAge,m.moving),spec=SPECS['crew-'+m.pilot+'-'+m.arsenal.selected],row=Math.floor(frame.direction/spec.cols)+(Math.floor(m.walkAge*9)%(spec.walkFrames||4))*(16/spec.cols);changeFrame(m.sprite,atlas.frame('crew-'+m.pilot+'-'+m.arsenal.selected,frame.direction%spec.cols,m.moving?row:Math.floor(frame.direction/spec.cols)));m.sprite.position.set(p.x,p.y,p.z);m.sprite.scale.set(2.6,p.hp>0?2.6:1.1,1);m.sprite.material.rotation=p.hp>0?0:Math.PI/2;m.sprite.material.opacity=p.dead?.4:1;m.sprite.material.color.set(p.down?'#bca38f':'#ffffff');}
 $('crew-status').textContent=net.active?crew.map(m=>PILOTS[m.pilot].name.toUpperCase()+' '+(m.player.down?'DOWN '+Math.round(m.player.revive/3*100)+'%':m.player.dead?'REDEPLOY':mode==='coop'?Math.ceil(m.player.hp)+'%':m.frags+' / '+m.deaths)).join('\n'):'';
}
function checkMatch(){if(ending)return;if(mode==='coop'&&crew.length&&livingCrew().length===0)finish(false);if(mode==='ffa'&&(crew.some(m=>m.frags>=20)||matchTime>=600)){finish(true);const sorted=[...crew].sort((a,b)=>b.frags-a.frags||a.deaths-b.deaths);$('ending-title').textContent=PILOTS[sorted[0].pilot].name.toUpperCase()+' WINS';$('outcome').textContent=sorted.map(m=>PILOTS[m.pilot].name.toUpperCase()+' / '+m.frags+' FRAGS / '+m.deaths+' DEATHS').join('\n');$('next').textContent='REMATCH';}if(net.active&&net.role==='guest')$('next').hidden=true;}
function navigationGoal(){if(mode==='ffa')return livingCrew().filter(m=>m.id!==net.self).sort((a,b)=>Math.hypot(a.player.x-player.x,a.player.z-player.z)-Math.hypot(b.player.x-player.x,b.player.z-player.z))[0]?.player;if(!tasks.solved)return tasks.goal(player);if(!world.accessCard.taken)return world.accessCard;if(!world.puzzle.solved)return world.switches.find(s=>s.index===world.puzzle.order[world.puzzle.input.length]);if(!mission.record)return world.control;const gate=world.gates.find(g=>g.id==='security'&&!g.open);if(gate)return gate;const boss=actors.find(a=>ACTORS[a.type].tier==='BOSS'&&a.hp>0);return boss?{x:boss.x,z:boss.z,y:boss.groundY}:world.exit;}
function updateNavigation(dt){
 const primary=navigationGoal();guide.update(player,primary,dt);
 const targets=compassTargets({world,tasks,mission,primary,cases,pickups,actors,crew,self:net.self,mode});
 compassView.render(compass.update(player,targets,dt,guide),player.yaw);
 const readout=$('route-guide');readout.textContent=guide.next?(guide.action.includes('LIFT')||guide.action.startsWith('RIDE')?guide.action:Math.ceil(guide.distance)+'m'+(guide.elevation>.45?' ↑':guide.elevation<-.45?' ↓':'')):'';
}

function emitVisual(kind,data){if(net.active&&net.role==='host'){netEvents.push({id:++eventSerial,kind,data});if(netEvents.length>80)netEvents.shift();}}
const dataOnly=o=>Object.fromEntries(Object.entries(o).filter(([k,v])=>!['sprite','mesh','waypoint'].includes(k)&&typeof v!=='function'));
function sceneState(){return{layoutVersion:world.layoutVersion,chapter:chapterIndex,seed:baseSeed,pilot,score,player:{...player},arsenal:{slots:arsenal.slots,selected:arsenal.selected},actors:actors.map(dataOnly),nests:nests.map(dataOnly),infestation:infestation.snapshot(),cases:cases.map(dataOnly),pickups:pickups.map(dataOnly),gates:world.gates.map(dataOnly),lifts:world.lifts.map(dataOnly),switches:world.switches.map(dataOnly),secrets:world.secrets.map(dataOnly),puzzle:world.puzzle,key:world.accessCard.taken,bridge:bridgeAdded,mission,tasks:tasks.snapshot(),campaign,storyEvents:[...storyEvents],radio:{active:radio.active,queue:radio.queue,seen:[...radio.seen],history:radio.history,elapsed:radio.elapsed},elapsed};}
function networkSnapshot(){localCrew().score=score;return{...sceneState(),crew:crew.map(m=>({id:m.id,pilot:m.pilot,player:{...m.player},arsenal:{slots:m.arsenal.slots,selected:m.arsenal.selected,reload:m.arsenal.reload,cooldown:m.arsenal.cooldown},visor:{stains:m.visor.stains,active:m.visor.active?{...m.visor.active,ids:[...m.visor.active.ids]}:null,palette:m.visor.palette,cooldown:m.visor.cooldown},score:m.score,frags:m.frags,deaths:m.deaths,walkAge:m.walkAge,moving:m.id===net.self?!!(localInput().forward||localInput().strafe):m.moving,notice:m.notice})),radio:{active:radio.active,elapsed:radio.elapsed,queue:radio.queue,seen:[...radio.seen],history:radio.history},projectiles:projectiles.map(dataOnly),waves:waves.map(dataOnly),events:netEvents,ending:ending?{success:mission.complete,title:$('ending-title').textContent,label:$('ending-label').textContent,text:$('outcome').textContent}:null,matchTime};}
function applyState(s){
 mission=structuredClone(s.mission);tasks.restore(s.tasks);infestation.restore(s.infestation);growthVisuals.update();world.accessCard.taken=!!s.key;Object.assign(world.puzzle,s.puzzle);for(const name of ['gates','lifts','switches','secrets'])for(let i=0;i<world[name].length;i++)if(s[name]?.[i])Object.assign(world[name][i],s[name][i]);if(s.bridge&&!bridgeAdded){world.bridge();buildArchitecture();bridgeAdded=true;}elapsed=s.elapsed||0;campaign=s.campaign||[];storyEvents=new Set(s.storyEvents||[]);if(s.radio){const dismissed=radio.dismissed;Object.assign(radio,{history:[],...s.radio});radio.seen=new Set(s.radio.seen||[]);radio.dismissed=dismissed;}
 const old=new Map(actors.map(a=>[a.id,a]));actors=(s.actors||[]).filter(a=>ACTORS[a.type]).map(raw=>{let a=old.get(raw.id);if(a)old.delete(raw.id);else{a=makeActor(raw.type,raw.x,raw.z);a.sprite=billboard(atlas.actor(raw.type,raw.state,raw.age,raw.duration),raw.x,raw.z,ACTORS[raw.type].size,raw.groundY);}Object.assign(a,raw);return a;});for(const a of old.values()){scene.remove(a.sprite);a.sprite.material.dispose();}
 for(let i=0;i<nests.length;i++)if(s.nests?.[i])Object.assign(nests[i],s.nests[i]);for(let i=0;i<cases.length;i++)if(s.cases?.[i])Object.assign(cases[i],s.cases[i]);
 for(let i=0;i<(s.pickups||[]).length;i++){const raw=s.pickups[i];let p=pickups[i];if(!p)p=addPickup(raw.kind,raw.gun,raw.x,raw.z,raw.delay,raw.amount);Object.assign(p,raw);p.sprite.visible=!p.taken;}while(pickups.length>(s.pickups||[]).length){const p=pickups.pop();scene.remove(p.sprite);p.sprite.material.dispose();}
}
function receiveFrame(s){if(!s||!running)return;applyState(s);matchTime=s.matchTime;for(const raw of s.crew||[]){const m=crew.find(m=>m.id===raw.id);if(!m)continue;const own=m.id===net.self,oldHp=m.player.hp,aim={yaw:m.player.yaw,pitch:m.player.pitch};Object.assign(m.player,raw.player);if(own&&!raw.player.dead&&!raw.player.down)Object.assign(m.player,aim);const desired=m.arsenal.selected;Object.assign(m.arsenal,raw.arsenal);if(own&&m.arsenal.slots[desired]?.owned)m.arsenal.selected=desired;m.score=raw.score;m.frags=raw.frags;m.deaths=raw.deaths;m.walkAge=raw.walkAge;m.moving=raw.moving;Object.assign(m.visor,raw.visor);if(m.visor.active)m.visor.active.ids=new Set(raw.visor.active.ids);if(own){score=m.score;if(oldHp>m.player.hp)damageFlash=.3;if(raw.notice&&raw.notice.id!==m.lastNotice){m.lastNotice=raw.notice.id;toast(raw.notice.text);}}}
 if(s.radio){const dismissed=radio.dismissed;Object.assign(radio,s.radio);radio.seen=new Set(s.radio.seen);radio.dismissed=dismissed;}
 const oldP=new Map(projectiles.map(p=>[p.id,p]));projectiles=(s.projectiles||[]).map(raw=>{let p=oldP.get(raw.id);if(p)oldP.delete(raw.id);else{p={mesh:effectSprite(atlas,raw.row,0,raw.x,raw.y,raw.z,raw.radius*4.6+.45)};scene.add(p.mesh);}Object.assign(p,raw);return p;});for(const p of oldP.values()){scene.remove(p.mesh);p.mesh.material.dispose();}
 const oldW=new Map(waves.map(w=>[w.id,w]));waves=(s.waves||[]).map(raw=>{const w=oldW.get(raw.id)||{};oldW.delete(raw.id);Object.assign(w,raw);return w;});for(const w of oldW.values())if(w.mesh)removeEffect(w);
 for(const e of s.events||[])if(e.id>lastEvent){lastEvent=e.id;const d=e.data;if(e.kind==='gore')enemyHit(d.actor,d.point,d.lethal);if(e.kind==='decal')floorSplatter(d.x,d.z,d.color,d.size);if(e.kind==='ring')ring(d.x,d.z,d.color,d.max,d.duration,d.y);if(e.kind==='enemySound')sfx.enemy(ACTORS[d.type],d.kind,d.position);if(e.kind==='beam')beam(d.from,d.to,d.color,d.life,d.width);if(e.kind==='tracer')shotTracer(d.from,d.to,WEAPON_BY_ID[d.gun]);if(e.kind==='particles')particleBurst(d.x,d.y,d.z,d.color,d.count,d.power);if(e.kind==='burst')spriteBurst(d.x,d.y,d.z,d.row,d.size);if(e.kind==='sound'){sfx.weapon(d.gun,{position:d.position});if(d.shooter===net.self)recoil=1;}}
 if(s.ending&&!ending){ending=true;paused=true;shooting=false;document.exitPointerLock?.();$('ending').hidden=false;$('pause').hidden=true;$('ending-title').textContent=s.ending.title;$('ending-label').textContent=s.ending.label;$('outcome').textContent=s.ending.text;$('next').hidden=true;}
}
function updateGuest(dt){elapsed+=dt;radio.update(dt);arsenal.update(dt);wipePose=visor.update(dt);recoil=Math.max(0,recoil-dt*8);damageFlash=Math.max(0,damageFlash-dt);toastTime=Math.max(0,toastTime-dt);hitTime=Math.max(0,hitTime-dt);wheelCooldown=Math.max(0,wheelCooldown-dt);const movement=movePlayer(player,world,dt,localInput());if(movement.moving)bob+=dt*movement.speed*1.3;camera.position.set(player.x,player.y+(player.down?.7:1.65),player.z);camera.rotation.set(player.pitch,player.yaw,0);sfx.setListener(player);for(const a of actors){a.age+=dt;const d=ACTORS[a.type];changeFrame(a.sprite,atlas.actor(a.type,a.hitFlash>0&&a.hp>0?'hurt':a.state,a.age,a.duration));a.sprite.position.set(a.x,(a.groundY||0)+a.y+(d.hover&&a.hp>0?d.hover+Math.sin(elapsed*4+a.id)*.11:0),a.z);}for(const n of nests){changeFrame(n.sprite,n.machine?atlas.frame('legacyProps',Math.floor(n.age*5)%4,0):nestFrame(n));n.sprite.scale.y=n.state==='husk'?.65:n.variant===2?3.45:2.9;}for(const c of cases)changeFrame(c.sprite,atlas.frame('pickups',c.open?Math.min(7,Math.floor(c.age*9)):0,2));for(const p of projectiles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.z+=p.vz*dt;p.age+=dt;p.mesh.position.set(p.x,p.y,p.z);changeFrame(p.mesh,atlas.frame('attackVfx',Math.floor(p.age*16)%8,p.row));}for(const w of waves){w.age+=dt;if(w.age<0)continue;w.radius=w.kind==='pool'?1.8:w.age*8;updateWaveVisual(w);}advanceEffects(dt);levelVisuals.update(dt);stationVisuals.update(elapsed,player,paused?null:sfx,world);for(const p of infestation.patches)p.age+=dt;growthVisuals.update();tasks.clock+=dt;taskVisuals.update(camera);updateLights(dt);updateCrewSprites(dt);updateNavigation(dt);drawHud();}
function networkEvent(e){if(e.type==='connecting')$('room-status').textContent='CONNECTING…';if(e.type==='lobby'){refreshRoom();if(!net.active&&running)returnTitle(false);}if(e.type==='error'){$('room-status').textContent=e.message;toast(e.message);refreshRoom(false);}if(e.type==='hostLost'){toast('HOST CONNECTION LOST');returnTitle(false);$('room-status').textContent='HOST CONNECTION LOST / REJOIN FROM THE TITLE SCREEN';}if(e.type==='left'){const m=crew.find(m=>m.id===e.id);if(m?.sprite){scene.remove(m.sprite);m.sprite.material.dispose();}crew=crew.filter(m=>m.id!==e.id);}if(e.type==='start'){const {seed,chapter,keep}=e.settings;$('seed').value=seed;$('theme').value=chapter;setup(seed,chapter,keep);running=true;paused=false;ending=false;$('menu').hidden=true;$('pause').hidden=true;$('ending').hidden=true;$('next').hidden=true;document.body.classList.remove('menu-open');sfx.unlock();sfx.setPaused(false);}if(e.type==='frame')receiveFrame(e.state);}
function refreshRoom(status=true){if(status)$('room-status').textContent=net.code?'ROOM '+net.code+' / '+(net.mode==='coop'?'CO-OP':net.mode==='ffa'?'FREE-FOR-ALL':'RIVAL RECOVERY')+(net.role==='guest'?'\nWAITING FOR HOST':'\nSHARE THIS CODE WITH YOUR CREW'):'';$('room-roster').textContent=net.members.map(m=>PILOTS[m.pilot].name.toUpperCase()+(m.id==='host'?' / HOST':'')).join('\n');$('room-deploy').hidden=net.role!=='host'||!net.peer?.open;$('room-leave').hidden=net.role==='solo';$('host-room').disabled=net.role!=='solo';$('join-room').disabled=net.role!=='solo';}
function returnTitle(leave=true){controller.suspend();controllerMenu.clear();if(mode==='solo'&&running&&!ending)saveCampaign(false);running=false;paused=false;ending=false;shooting=false;keys.clear();document.exitPointerLock?.();if(leave){if(net.role==='host')net.returnToLobby();else net.leave();}sfx.setPaused(true);$('ending').hidden=true;$('pause').hidden=true;$('menu').hidden=false;$('next').hidden=false;document.body.classList.add('menu-open');refreshRoom();refreshSaves();populateChapters();}
function saveCampaign(manual=false,completed=false){if(!ready||mode!=='solo'||!running||player.hp<=0||ending&&!completed)return false;try{saves.save(Number($('save-slot').value),sceneState(),CHAPTERS[chapterIndex].title);if(manual)toast('RECOVERY SAVED');refreshSaves();return true;}catch(e){if(manual)toast('SAVE FAILED / '+e.message);return false;}}
function refreshSaves(){const save=saves.load(Number($('save-slot').value));$('save-description').textContent=save?save.label.toUpperCase()+'\n'+new Date(save.savedAt).toLocaleString()+'\nSCRAP '+save.state.score:'EMPTY RECOVERY SLOT';$('load-save').disabled=!save;$('export-save').disabled=!save;}
function loadCampaign(){controller.suspend();const save=saves.load(Number($('save-slot').value));if(!save)return false;net.leave();const s=save.state;entryLoadout=null;entryScore=0;pilot=s.pilot;$('pilot').value=pilot;$('seed').value=s.seed;$('theme').value=s.chapter;setup(s.seed,s.chapter,false,s.layoutVersion??2);applyState(s);Object.assign(player,s.player,{down:false,dead:false,hurtCooldown:2,vy:0});clearStationOverlap(world,player);Object.assign(arsenal,s.arsenal);score=s.score;localCrew().score=score;running=true;paused=false;ending=false;$('menu').hidden=true;$('pause').hidden=true;$('ending').hidden=true;document.body.classList.remove('menu-open');camera.position.set(player.x,player.y+1.65,player.z);camera.rotation.set(player.pitch,player.yaw,0);sfx.unlock();sfx.setPaused(false);if(mission.complete)finish(true);else{syncMissionProgress();const key=mission.progressKey;mission.progressKey=null;syncMissionProgress();mission.progressKey=key;radio.send({id:'resume-'+chapterIndex,speaker:'ROOK',chapter:CHAPTERS[chapterIndex].title,text:tasks.solved?mission.record?CHAPTERS[chapterIndex].guardian:CHAPTERS[chapterIndex].intro:tasks.objective(),priority:true});}return true;}
$('host-room').onclick=()=>net.create($('pilot').value,$('net-mode').value);$('join-room').onclick=()=>net.join($('room-input').value,$('pilot').value);$('room-deploy').onclick=()=>{campaign=[];entryScore=score=0;entryLoadout=null;start();};$('room-leave').onclick=()=>{net.leave();refreshRoom();};$('leave-game').onclick=()=>returnTitle();$('save-game').onclick=()=>saveCampaign(true);$('load-save').onclick=loadCampaign;$('save-slot').onchange=refreshSaves;$('export-save').onclick=()=>{try{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([saves.export(Number($('save-slot').value))],{type:'application/json'}));a.download='Scrapper-Recovery-Slot-'+(Number($('save-slot').value)+1)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);}catch(e){toast(e.message);}};$('import-save').onclick=()=>$('save-file').click();$('save-file').onchange=async()=>{const file=$('save-file').files[0];if(!file)return;try{saves.import(await file.text(),Number($('save-slot').value));refreshSaves();}catch(e){$('save-description').textContent=e.message;}};

function shotTracer(from,to,w){
 emitVisual('tracer',{from:{...from},to:{...to},gun:w.id});
 if(w.mode==='flame'){
  const distance=Math.hypot(to.x-from.x,to.y-from.y,to.z-from.z),life=Math.max(.16,Math.min(.46,distance/22));
  for(let i=0;i<3;i++){const mesh=effectSprite(atlas,0,1,from.x,from.y,from.z,.7,'#ffffff','areaVfx');mesh.material.rotation=(i-1)*.2;scene.add(mesh);effects.push({mesh,age:i*.016,life:life+i*.035,flame:true,tracer:true,from:{...from},to:{x:to.x,y:to.y+(i-1)*.16,z:to.z}});}
  lights.flash(from,'#ffb947',16,.16,13);lights.flash(to,'#ff8e29',12,.22,12);return;
 }
 const row=w.id==='rockets'?3:w.id==='arc'||w.id==='blades'?1:2,size=w.id==='rockets'?.6:w.id==='beam'?.4:.34,mesh=effectSprite(atlas,row,0,from.x,from.y,from.z,size,w.id==='frost'?'#c7faff':'#ffffff');scene.add(mesh);effects.push({mesh,age:0,life:Math.max(.12,Math.min(.5,Math.hypot(to.x-from.x,to.y-from.y,to.z-from.z)/(w.id==='rockets'?38:80))),vfx:row,tracer:true,from:{...from},to:{...to}});
}

function syncMissionProgress(){if(mode==='ffa')return;if(world.puzzle.required===false&&tasks.solved)world.puzzle.solved=true;const bossAlive=actors.some(a=>ACTORS[a.type].tier==='BOSS'&&a.hp>0),key=!tasks.powered?'couplers-'+tasks.taken.length:!tasks.solved?'system-'+tasks.kind:!world.accessCard.taken?'access':!world.puzzle.solved?'relays':!mission.record?'archive':bossAlive?'guardian':'extract';if(mission.progressKey===key)return;const first=!mission.progressKey;mission.progressKey=key;guide.timer=0;if(first)return;const text=key.startsWith('couplers')?tasks.taken.length===2?'Both couplers recovered. Install them on the control deck.':'One coupler recovered. Follow the route to the second.':key.startsWith('system')?tasks.objective()+'. The auxiliary system must be restored before extraction.':key==='access'?CHAPTERS[chapterIndex].system:key.startsWith('relays')?'Blue access secured. Follow the sequence shown on the relay diagram.':key==='archive'?'The grid is online. Recover the archive and choose where its power goes.':key==='guardian'?CHAPTERS[chapterIndex].guardian:storyMessage(chapterIndex,'aftermath',{results:campaign,mission}).text;radio.send({id:'progress-'+chapterIndex+'-'+key,speaker:'ROOK',chapter:CHAPTERS[chapterIndex].title.toUpperCase(),text,priority:true});saveCampaign(false);}
