// Long-form recovery files live in the existing contract journal. Field logs stay brief.
export const CASE_FILES=[
 {
  background:[
   'Before Dock Nine, Rook recovered other people’s mistakes: a freighter with its docking clamps welded shut, a flooded refinery, a tug nobody had paid to tow home. He measures a job in working seals, return routes and the weight his suit can carry. The recovery union calls him Scrapper because he brings back the pieces that everyone else has written off.',
   'This contract is supposed to cover an overdue suit overhaul. The station owner wants the navigation ledger before its insurers sell the cargo. Echo, the union dispatcher, notices that the crew list was removed from the job packet. Rook adds “confirm occupancy” to his own checklist. Empty is an inspection result, not a promise in an invoice.'
  ],
  caseTitle:'DOCK NINE / THE OMITTED CREW',
  evidence:'The local manifest still holds the names stripped from the remote copy. A shift engineer reported swollen insulation six days before the station was declared empty. The reply authorized continued loading and classified her report as a humidity fault. Three outgoing lots share the carrier code V-17. Rook attaches the unedited ledger and the crew list to his salvage claim; deleting the station’s remote record will no longer delete their names.',
  system:'Freight power is back. Someone isolated the crew decks and left the loaders running. That is a choice somebody made. I want the ledger that explains it.',
  aftermath:'The freight doors are clear. I came for a ledger; I’m leaving with a crew list. Echo needs both before anyone can call this station empty again.',
  secret:'A hand-written shift roster behind the panel. The remote manifest had no crew. These people had names. I’m keeping this.',
  preserve:'I’m leaving the tissue records intact. More things can hatch while I get out, but the next crew needs to know what killed this one.',
  purge:'Purge authorized. The live records are gone; the manifest is already copied. I can close a hatchery. I cannot pretend that answers the whole question.'
 },
 {
  background:[
   'Echo traces V-17 to Verdant Array. The laboratory advertised a self-repairing agricultural substrate that could restore exhausted station gardens. Its biologists called the burrowing organism the Verdant Brood. Their containment notes describe a problem management’s sales material calls “rapid establishment.”',
   'Rook agrees to recover the notebooks because the next shipment is already in transit. Flint, an old maintenance partner, sends a warning about the purge system: its heat will destroy the local research storage along with the living cultures. The clean manifest can survive either choice. The observations that might teach someone to contain the Brood cannot.'
  ],
  caseTitle:'VERDANT ARRAY / THE WITHDRAWN WARNING',
  evidence:'Biologist Iona Vale ordered V-17 recalled when a culture began turning cable insulation into egg chambers. Her withdrawal request was filed under an obsolete shipment number, so the loading system never received it. Her final notes distinguish a feeding growth from an ordinary root and describe a sterilization test that almost worked. She left the unfinished result attached to the recall. Rook records the difference between an incomplete experiment and an absent warning.',
  system:'The archive sorter is working. Vale put the recall in the same queue as the cargo. Someone changed the queue, not her warning.',
  aftermath:'The roots have stopped pushing against the archive door. Vale did her job. I have to get enough of it home for someone to finish it.',
  secret:'A duplicate recall, hidden with the spare filters. Vale knew the official copy might vanish. I’m adding it to the claim.',
  preserve:'Vale’s observations are staying intact. The hatcheries will stay active too. I will take that risk on my way out, not leave it for another crew.',
  purge:'The cultures are burning. I copied the recall first, but the experiment notes were tied to the live bank. Containment now; fewer answers later.'
 },
 {
  background:[
   'Glacier Works received cultures recalled from Verdant Array and froze them instead of returning them. The storage crews assumed that quiet specimens were contained specimens. A second organism grew through mineral deposits around the coolant lines, using the pipes and sensors as a resonator.',
   'EOS, Rook’s survey intelligence, finds a regular pulse in the station telemetry. It appears before every pressure excursion, but it is not generated by the pumps. Rook starts keeping two lists: damage that machinery caused, and damage something caused by making the machinery move. The second list keeps getting longer.'
  ],
  caseTitle:'GLACIER WORKS / THE SIGNAL UNDER THE ALARM',
  evidence:'The refrigeration log contains a repeating interval beneath the ordinary compressor noise. It matches the openings of several specimen containers that were supposed to be mechanically isolated. The glass growth is communicating; the Brood is responding. The two organisms arrived under different cargo descriptions but shared a carrier gel. EOS preserves the raw timing instead of merely filtering it out as interference. The signal itself may become a tool for detecting contamination.',
  system:'That frequency is the carrier signal. EOS has its shape now. Turning an alarm down did not make the thing behind it disappear.',
  aftermath:'The reservoir has gone quiet. I’m leaving the recorder on. Quiet needs a time stamp before I trust it.',
  secret:'A technician kept an unfiltered recording in a service cache. Every official diagnostic erased the same “noise.” This copy didn’t.',
  preserve:'Keep the timing records. If the Choir talks through machinery, the recordings may tell us which machines are already listening.',
  purge:'The resonance bank is purged. EOS has the basic signal, but the long recordings are gone. We can recognize it; we may miss its variations.'
 },
 {
  background:[
   'At Cinder Foundry, autonomous equipment is producing security drones against purchase orders that nobody issued. The factory’s records still show normal staffing. Its actual workstations contain empty suits and actuator housings lined with living conductive threads.',
   'Flint recognizes the infected gel as an additive from the same V-17 supply catalog. The Iron Splice is a third organism, built to exploit interfaces the other two cannot reach. Rook’s knowledge of lockouts and maintenance clearances becomes more useful than the official security response. The union changes his classification to infestation recovery specialist while he is still inside.'
  ],
  caseTitle:'CINDER FOUNDRY / THREE PRODUCTS, ONE CARRIER',
  evidence:'The sales catalog offered root repair, acoustic fault detection and adaptive actuator gel as separate products. Their raw materials came from the same carrier line. The Brood makes habitat, the Choir coordinates activity, and the Splice turns repair machinery into transport and protection. There is no single creature giving orders to the other two. The product made it easy for three different species to use one another’s work. The company sold the combination without understanding the consequences.',
  system:'Decontamination passed. The gel is in the actuators on the other side of the seal. A clean air sample never tested the machines.',
  aftermath:'The controller is down. Flint has the gel specification. I now know three kinds of infestation, and exactly how much the supplier left out.',
  secret:'A discarded maintenance order names a live gel substitution. Somebody signed for it. Another page for the lien.',
  preserve:'Keep the fabrication records. Clean stations use these same actuators. They need a way to inspect them before they fail.',
  purge:'Fabrication cultures purged. Flint will have to reverse-engineer a clean substitute from the specifications I recovered.'
 },
 {
  background:[
   'The calls stop being invitations to inspect abandoned property. Occupied stations ask Rook what a contaminated crate looks like. He sends pictures of damaged seals, feeding arches and the labels from Dock Nine. He is careful to include what he still does not know.',
   'Port Meridian continues to issue clean transit certificates. Echo finds that its inspection software accepts a certificate issued by the cargo’s sender. Rook enters through a service dock because bonded storage is officially closed to investigators. His salvage license gets him through a door that a warning notice did not.'
  ],
  caseTitle:'PORT MERIDIAN / APPROVED AFTER THE WARNING',
  evidence:'The loading crane’s local queue retains the original departure times. They are later than Vale’s recall, later than the first station loss, and earlier than the forged inspections now attached to them. The same commercial authority approved both documents. Rook copies the queue before moving the cargo. The record does not prove that every handler knew what was inside; it does prove that the warning reached the people who kept the line open.',
  system:'The crane log survived the rewritten manifests. These loads departed after the recall. I have the original times, not another argument.',
  aftermath:'The bonded doors are clear. Echo has a copy and EOS has a second. They can dispute my invoice. They cannot quietly lose the evidence.',
  secret:'An inspection stamp under a false floor. The serial matches a supposedly destroyed terminal. That makes the forged certificates traceable.',
  preserve:'Preserve the inspection bank. Every surviving signature is another station we can warn before its freight arrives.',
  purge:'Purge the hatcheries. The departure queue is copied; some inspection trails will end here. I’ll mark those gaps instead of filling them in.'
 },
 {
  background:[
   'The emergency relay at Kestrel Sump accepted the last evacuation traffic from several affected stations. It now broadcasts the same request at perfect intervals. The recording includes an intake of breath, a scrape against a microphone and a destination that stopped operating years ago.',
   'Echo recognizes the opening words as an old union rescue drill. Rook goes below the relay to recover the separate raw tracks. The Choir does not need to understand a plea for help to learn that the sound opens doors. He needs to distinguish a recording from a person without teaching himself to ignore people.'
  ],
  caseTitle:'KESTREL SUMP / TWO CALLS ON ONE CHANNEL',
  evidence:'The black box separates real evacuation traffic from later imitations. Human callers change the rhythm, answer interruptions and supply new information. The Choir’s repetitions preserve details even when they no longer make sense. EOS builds a challenge-and-response check from the real track; it does not reduce the problem to a rule that every repeated message is false. Rook sends the check with a warning to verify before approaching, not an instruction to stop answering.',
  system:'The playback order separates the two tracks. One was a crew asking for help. The other kept asking after the microphones lost power.',
  aftermath:'The marshal is silent. Echo is transmitting the verification check. We can keep answering calls without following every voice into a hatchery.',
  secret:'A rescue drill on an isolated recorder. That is where the imitation learned its opening line. The real call starts differently.',
  preserve:'Keep the raw calls. The safe check depends on variation, not just one pattern I happened to survive.',
  purge:'The resonance bank is gone. The copied evacuation track stays with EOS, but we lose the longer comparison. Verify every call twice.'
 },
 {
  background:[
   'Habitat Seven has working shelter circuits and a garden that is consuming the structure around it. Rook can read the damage now: ordinary roots draw water; Brood arches turn the ductwork into a nursery. Both are threaded through the same air system.',
   'He is no longer deciding only what fits in his salvage pack. The research bank could help other habitats separate a garden from a hatchery. Keeping it means leaving sources active while he works. Purging buys immediate breathing room and destroys the measurements that make a cleaner solution possible. Echo asks him to record the choice in his own words.'
  ],
  caseTitle:'HABITAT SEVEN / WHAT THE GARDEN WAS DOING',
  evidence:'Sensor records show the shelter air drawing through healthy beds and infected beds in the same loop. Vale’s surviving work, when available, gives the union a starting point for distinguishing them. The map is still valuable if the biological bank is purged, but it cannot substitute for the lost observations. Rook separates the guaranteed recovery—the route and system map—from the research whose fate he chooses. His report carries both, including the cost.',
  system:'The shelter sensor grid is mapped. I can see which beds share the air loop. The people outside need that map, whatever I choose about the samples.',
  aftermath:'One passage is open through the garden. I marked the live roots on the map. “Cleared” is too small a word for what is still here.',
  secret:'Someone marked safe air returns on the back of a panel. They were maintaining the shelters after the station stopped paying them.',
  preserve:'I’m preserving the growth study. The sources stay active on this extraction, but the next habitat may get a way to save both its air and its records.',
  purge:'I’m purging the bank. That reduces the sources here and destroys a chance to study them. Write both things down, Echo. Neither cancels the other.'
 },
 {
  background:[
   'The Orison repair yard keeps supplying emergency actuators to stations that cannot afford to wait. Its infected machines repeat routines taught by workers who are no longer present. Flint recognizes one tool change as a shortcut he once recommended to the yard.',
   'Rook needs the distribution keys so the union can isolate contaminated stock without abandoning every clean station waiting for a part. EOS marks the infected control gel, but cannot promise that a familiar movement means a familiar mind is still inside. Rook stops watching the machines for a sign of recognition and starts watching for their next attack.'
  ],
  caseTitle:'ORISON YARD / A ROUTINE IS NOT A SURVIVOR',
  evidence:'The yard’s learning controller stores motion traces separately from personnel records. The Splice has copied the traces and uses them to keep the line moving. The distribution keys identify which orders included live gel and which used sealed mechanical stock. Flint can organize a smaller clean supply chain from the latter. It will not replace everything at once, but shutting down the infected line need not mean shutting down repair itself.',
  system:'Loads are balanced across the clean circuits. Flint can read the distribution keys now. We can quarantine the gel without writing off every spare part.',
  aftermath:'The controller has stopped repeating that tool change. Flint says he has enough to start a clean line. Good. Give him work that stays repaired.',
  secret:'A sealed manual parts list, older than the adaptive gel. Flint can use this. Sometimes the obsolete version is the one that still works.',
  preserve:'Preserve the machine-learning records. Flint can compare the contaminated routines with the clean stock before restarting anything.',
  purge:'Purge the live control bank. The distribution keys survive, but Flint has to rebuild its inspection routines by hand.'
 },
 {
  background:[
   'Dock Nine is scheduled for demolition under a clause that allows the owner to destroy unsafe assets. Rook’s earlier ledger points to a sealed approval archive that was never included in the recovery contract. Echo discovers that the original fee was issued after the owner received a contamination report.',
   'Rook returns knowing the maintenance routes he once used only to escape. All three strains now occupy the station. His license places recovered records under a temporary lien until the claim is heard. The small clause he normally uses to get paid is now the reason the owner cannot demand that he surrender the only copy.'
  ],
  caseTitle:'DOCK NINE / THE PRICE OF THE FIRST CONTRACT',
  evidence:'The approval archive contains the original trial order, the first contamination report and the price comparison used to authorize Rook’s contract. A salvage inspection was cheaper than a quarantine response. His arrival would either recover valuable records or produce another missing contractor entry. The records identify responsibility without explaining every motive. Rook keeps the originals under his license and sends verified copies to the union before leaving the station again.',
  system:'The stabilization record predates my contract. They knew this station was contaminated when they hired me to certify its cargo.',
  aftermath:'Same freight doors. This time the records are already off-station. I’m leaving on my terms, and the crew list is still attached.',
  secret:'My own job number in an internal cost sheet. They priced a replacement suit lower than a quarantine team. I kept the receipt.',
  preserve:'Preserve the approval bank. My claim carries the original trial order, and anyone disputing it can argue with a complete record.',
  purge:'The live bank is purged. I copied the approval signatures first. There will be gaps in the experiment history, not in who authorized it.'
 },
 {
  background:[
   'The freight evidence leads to the seed vault that supplied the V-17 carrier line. Vale’s work was part of a wider attempt to combine three useful biological behaviors. The surviving notes also contain the first serious attempt to separate them again.',
   'Rook arrives with a record shaped by his own choices. Preserved banks provide observations the vault can cross-check. Purged banks leave absences that no recovered memo can honestly fill. The isolation procedure is still worth recovering. A procedure with named limits is better than an assurance that a product is safe because nobody has finished proving otherwise.'
  ],
  caseTitle:'THE SEED VAULT / THE SEPARATION PROCEDURE',
  evidence:'The isolation notes describe three separate jobs: remove carrier tissue, break the Choir’s coordinating signal, and quarantine gel-bearing machinery. Each job can succeed while the other two remain unfinished. The matching sample chambers provide the missing separation order. Preserved research supplies a wider basis for validation; purged research means more of the procedure will need to be retested under containment. Rook labels the gaps and transmits the complete source rather than a simplified guarantee.',
  system:'Samples separated. Brood tissue, Choir crystal, Splice gel. Three containment jobs. Killing one source never proved the other two were gone.',
  aftermath:'The vault is accessible. I have the procedure and its missing pages marked. Nobody is going to sell this as an easy fix again.',
  secret:'Vale’s annotations on a rejected protocol. She marked the failed trials as carefully as the successful ones. Those stay in the report.',
  preserve:'Preserve the isolation trials. Every intact observation is one less dangerous experiment another station has to repeat.',
  purge:'The live trial bank is purged. The isolation procedure is copied, with its validation gaps marked. The union must retest those steps before reopening.'
 },
 {
  background:[
   'The cold backbone links clean emergency channels to contaminated relays. The Choir uses the same paths to coordinate outbreaks. Cutting all traffic would stop some signals and abandon the callers Rook has spent this campaign learning how to reach.',
   'Echo routes confirmed calls through the channels the recovery crew isolates. EOS applies the check recovered at Kestrel Sump when that record is available. Rook is still doing the work of a salvager: identify the damaged circuit, keep a return path, save what can function. The difference is how many people are waiting beyond the next switch.'
  ],
  caseTitle:'THE QUIET NETWORK / CALLS THAT ANSWER BACK',
  evidence:'After the optical channels are isolated, the relay begins carrying messages that change when challenged. The recovered route map distinguishes those channels from the Choir’s resonant paths. The black-box evidence from Kestrel strengthens the verification method when it is in the case record; otherwise the union must validate the callers through independent relays. Quiet is no longer the objective. A channel that real people can safely use is.',
  system:'The three channels are isolated. Echo has room to verify the real calls. Keep the emergency network alive; the Choir does not get every wire.',
  aftermath:'The marshal is down. Leave the receiver on. This time I want to hear what comes after the silence.',
  secret:'A service route bypasses the shared resonator. An old emergency design, still doing its job. EOS is saving the routing diagram.',
  preserve:'Keep the signal history. The union needs to test the safe channels against more than the calls we heard today.',
  purge:'The resonance bank is destroyed. The isolated emergency routes remain mapped. Confirm callers through a second relay until the checks are rebuilt.'
 },
 {
  background:[
   'The final carrier foundry is completing an automated distribution order. Its authority does not depend on an executive still answering calls: the shipment was authorized long ago, and every machine is waiting for the next machine to finish.',
   'Rook has become the person stations call when nobody knows whether a door is safe to open. He still carries the same salvage license. The last job is to stop the line, recover its dispatch keys and get the record out intact enough for others to continue. He does not have to repair every station himself. He has to leave them more than another sealed door.'
  ],
  caseTitle:'CARRIER FOUNDRY / THE LAST AUTOMATIC ORDER',
  evidence:'The dispatch controller will keep reproducing the original order until its local authority is disabled. The shutdown sequence cancels the active lot and isolates its keys. Shipping records connect that authority back to the trial approvals at Dock Nine. The material record determines how quickly the union can validate containment and restart clean repairs. The line can be stopped in a single shift. The recovery will take longer, and now somebody knows where to begin.',
  system:'Dispatch authority is disabled. The line cannot authorize another V-17 shipment. Now I get the keys past Parallax and close this contract.',
  aftermath:'Parallax is down. Dispatch keys, original approvals, recovery route. Check the pack, check the seal, get home. I know this part.',
  secret:'An unissued batch key in a locked service panel. Cancelled and logged. No unattended order is leaving behind a spare signature.',
  preserve:'Preserve the last carrier records. The foundry stops today; the people making the isolation protocol need everything we can bring back.',
  purge:'Purge the live carrier bank. The dispatch keys and copied approvals are enough to stop shipment. Rebuilding the science will take longer.'
 }
];
